### ISSUE TITLE
Restructure Libs for Dev Velocity

### ISSUE THREAD

**Issue by crutcher** [facebookresearch/fairscale#1003]
I've been talking with @min-xu-ai about restructuring internal libs towards dev velocity.

This is a tracking issue to hang sub-issues and diffs towards these ideas on.

The high-level structure I'd like to achieve is:
 * apis which users can call, and all their local deps are in `fairscale/`
 * apis which users should not call, but need to ship with fairscale, are in `fairscale/internal`
 * test and dev apis, which are permitted to have extra requirements, are in `fair_dev/`
 * Common scripts (repo bootstrap, structured parallel testing, dead code elimination, static analysis) get orchestrated with a common runner `./cmd NAME`, storing scripts in `commands/`, with docs.

With some additional polish, `fair_dev` and portions of `fairscale/internal` can be lifted into their own libs `fair_dev` and `fair_common` for use by other fair libs, and potentially other libs.

**Comment by min-xu-ai** [comment]
Nice plan! cc others too. @anupambhatnagar @riohib so that they also know. (BTW, I am on PTO for next week, so I won't be reviewing any PRs).

**Comment by h-vetinari** [comment]
This split is not very clean at the moment. `fair_dev` is not installed by default, but _is_ used by the tests, which meant that https://github.com/conda-forge/fairscale-feedstock/pull/20 (and follow ups) broke - I had no time to investigate earlier, but I'd say:
* either install `fair_dev` by default (or at least provide an option to do it)
* make the usage of `fair_dev` in the test conditional on the availability of `fair_dev`[^1]

[^1]: we run tests of the packages as-installed (which is necessary to test the artefacts as they will get distributed) but that's not the same as in-tree.

**Comment by min-xu-ai** [comment]
Thanks for letting us know that @h-vetinari . @crutcher, can you help fixing this?

**Comment by min-xu-ai** [comment]
@h-vetinari I moved fair_dev but I don't know if this is enough. Can you please kindly let us know? Thanks!

**Comment by h-vetinari** [comment]
> @h-vetinari I moved fair_dev but I don't know if this is enough. Can you please kindly let us know? Thanks!

Hi @min-xu-ai. Sorry for the delays, I had a very busy period.

I tested #1078 in https://github.com/conda-forge/fairscale-feedstock/pull/24, but it still runs into
```
E   ModuleNotFoundError: No module named 'fairscale.fair_dev'
```

What do I need to do so that `fair_dev` gets installed properly into `site-packages`?

**Comment by h-vetinari** [comment]
> I tested #1078 in [conda-forge/fairscale-feedstock#24](https://github.com/conda-forge/fairscale-feedstock/pull/24), but it still runs into [...]

I raised an issue: https://github.com/facebookresearch/fairscale/issues/1096
