### ISSUE TITLE
[test] benchmarks: check final model against golden checkpoint

### ISSUE THREAD

**Issue by msbaines** [facebookresearch/fairscale#104]
## 🚀 Feature

@myleott had an excellent suggestion. To test for regressions, we should check final model_params of the benchmark tests against a golden checkpoint.

## Motivation

Better regression testing.

## Pitch

Find regressions via unit tests instead of downstream.

**Comment by myleott** [comment]
Also, loading checkpoints and making sure they produce the same values for inference, particularly for things like model parallel.

We have a bunch of tests like this for checkpoints that we've released in fairseq (fairinternal link, sorry):
https://github.com/fairinternal/fairseq-py/blob/f1c3f2259ccd19dee6a2dfc12652b334a5f4b6eb/tests/fb_test_hub.py#L97-L98

**Comment by blefaudeux** [comment]
we're doing that against Pytorch in many places, I don't think that this still applies ? Closing, feel free to reopen if in need
