### ISSUE TITLE
AssertionError: expects all parameters to have same requires_grad

### ISSUE THREAD

**Issue by boundles** [facebookresearch/fairscale#1047]
`
import os
import torch
import torch.nn as nn
from torch.nn.parallel import DistributedDataParallel
import torch.distributed as dist
import torch.multiprocessing as mp

from fairscale.nn.data_parallel import FullyShardedDataParallel as FSDP

def init_dist(backend='nccl'):
    if backend == 'nccl':
        os.environ['NCCL_IB_DISABLE'] = '1'
        os.environ['NCCL_SOCKET_IFNAME'] = 'eth0'

    if mp.get_start_method(allow_none=True) is None:
        mp.set_start_method('spawn')

    local_rank = 0
    torch.cuda.set_device(local_rank)
    dist.init_process_group(backend=backend)

class Model(nn.Module):
   def __init__(self):
       super(Model, self).__init__()
       self.layer1 = nn.Linear(8, 4)
       self.layer2 = nn.Linear(4, 16)
       self.layer3 = nn.Linear(16, 4)
   
   def forward(self, x):
       return x

if __name__ == '__main__':
    init_dist(backend='nccl')
    model = Model()
    for param in model.layer1.parameters():
        param.requires_grad = False
    model = model.cuda()
    model = DistributedDataParallel(model)
    model = FSDP(model)
    print('ok')
`

Traceback (most recent call last):
  File "/home/luban/test_fairscale_fsdp.py", line 40, in <module>
    model = FSDP(model)
  File "/home/luban/miniconda3/lib/python3.9/site-packages/fairscale/nn/data_parallel/fully_sharded_data_parallel.py", line 382, in __init__
    self._fsdp_wrapped_module: nn.Module = FlattenParamsWrapper(module, param_list=to_be_flatten_params)
  File "/home/luban/miniconda3/lib/python3.9/site-packages/fairscale/nn/misc/flatten_params_wrapper.py", line 211, in __init__
    params, param_infos, shared_param_infos = self._init_flatten_params(new_p_set)
  File "/home/luban/miniconda3/lib/python3.9/site-packages/fairscale/nn/misc/flatten_params_wrapper.py", line 279, in _init_flatten_params
    assert len(set(p.requires_grad for p in params)) == 1, "expects all parameters to have same requires_grad"
AssertionError: expects all parameters to have same requires_grad
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 3429) of binary: /home/luban/miniconda3/bin/python

**Comment by min-xu-ai** [comment]
Yeah. This is expected. If you want to avoid this, please set flatten_parameters to False.

**Comment by boundles** [comment]
> Yeah. This is expected. If you want to avoid this, please set flatten_parameters to False.

ok, thanks a lot
