### ISSUE TITLE
Can fairscale run megatron-style model parallel combined with Gpipe?

### ISSUE THREAD

**Issue by eric-haibin-lin** [facebookresearch/fairscale#105]
Can fairscale run megatron-style model parallel combined with Gpipe?

**Comment by froody** [comment]
@eric-haibin-lin Yes, though there are some caveats and I need to write a tutorial. For now you can look at this test:

https://github.com/facebookresearch/fairscale/blob/master/tests/nn/model_parallel/test_layers.py#L310

Gpipe has two modes of operation: all stages in a single process, or 1 stage per process (see the `style` argument to `Pipe`). If you want to combine megatron and gpipe effectively, you'll need a minimum of 4 GPUs. If these GPUs aren't all on the same machine, then it is recommended to have the fastest link (e.g. NVLink on the same machine) between megatron peers, and the slower link (e.g. inter-host connection) between pipeline stages. This is done automatically by `initialize_model_parallel`.

**Comment by eric-haibin-lin** [comment]
thanks! I’ll take a look
