### ISSUE TITLE
How can I use only OSS in Pytorch lightning?

### ISSUE THREAD

**Issue by CD21a** [facebookresearch/fairscale#1053]
Hello

I wanna use only OSS (zero1) in pytorch lightning, but pytorch lightning only support OSS + SDP (zero2).
How can i use only OSS?

**Comment by min-xu-ai** [comment]
Thanks for reporting. Can you raise this issue to lightning repo? I don't think it is a question for fairscale. You can directly use OSS from fairscale without lightning and let us know if you have questions or not. Thanks.
