### ISSUE TITLE
Inconsistence in checkpoint-wrapper when wrapped BN block

### ISSUE THREAD

**Issue by yuctian** [facebookresearch/fairscale#1059]
I have fixed random seed.
The training phase were normal, but when I used checkpoint-wrapper, I got weird result. The output is quite different. This mainly happened when wrapped BN block. How to fix the problem.

**Comment by min-xu-ai** [comment]
BN is special. checkpoint wrapper must make sure its running stats is maintained only during one of the forward pass. You can see checkpoint wrapper code that does special things to BN.

**Comment by min-xu-ai** [comment]
please reopen if you have additional questions.
