### ISSUE TITLE
Question: VRAM Limits for FSDP across Asymmetrical GPUs?

### ISSUE THREAD

**Issue by zaptrem** [facebookresearch/fairscale#1073]
Hello, with HF Accelerate you can [limit GPU memory](https://huggingface.co/docs/accelerate/main/en/usage_guides/big_modeling#:~:text=First%20note%20that%20you%20can%20limit%20the%20memory%20used%20on%20each%20GPU%20by%20using%20the%20max_memory%20argument) usage on a per-GPU basis when sharding a model. This has proven extremely useful to me as I'm training with a set of GPUs that have different amounts of available VRAM due to hardware and software differences.

Is there a way to do this with Fairscale?

**Comment by min-xu-ai** [comment]
please reopen if there are more questions.

**Comment by zaptrem** [comment]
> But maybe you are asking that to shard in a way that different GPUs have different sizes of shards?

This is what I was curious about. I'm using the PyTorch Lightning Fairscale integration. Thank you for referring me in the right direction! I'll wait for what zhaojuanmao has to say.

**Comment by zhaojuanmao** [comment]
we do not support different shard sizes on different GPUs yet
