### ISSUE TITLE
is the prefetch_fsdp_params_simple branch deleted or merged?

### ISSUE THREAD

**Issue by hyoo** [facebookresearch/fairscale#1082]
I can't see it this morning. If this branch is deprecated, what would be the best branch to use?

This branch has been referenced from the metaseq repo, btw,
https://github.com/facebookresearch/metaseq/blob/main/Dockerfile#L40

**Comment by min-xu-ai** [comment]
oops, I didn't know it was used. I must have cleaned it up during the weekend. I just restored it. Please check it out and let me know if that's working or not.
