### ISSUE TITLE
Why I cannot set move_params_to_cpu=True

### ISSUE THREAD

**Issue by xdd12135** [facebookresearch/fairscale#1089]
I want to use the function move_params_to_cpu=True in the code,but I got the rrror as follows:

![image](https://user-images.githubusercontent.com/56624119/195483788-c8b8b09b-1bf0-423d-b2a6-25db633f2cba.png)

it seems the device should be on cpu,with move_params_to_cpu=True,however,I can't find the code to move the model to cpu. and I check the FSDP code in torch1.12, there's a function that move model to cpu.

my version:
torch==1.10
python==3.8
fairscale==0.4.12

here's my code
```
import os
import torch
import torch.distributed as dist
import torch.multiprocessing as mp
import torch.nn as nn
import torch.optim as optim
from torch.distributed.optim import ZeroRedundancyOptimizer
from torch.nn.parallel import DistributedDataParallel as DDP
from fairscale.nn.data_parallel import FullyShardedDataParallel as FSDP
from fairscale.nn.wrap import auto_wrap, enable_wrap, wrap ,default_auto_wrap_policy 
from functools import *
import functools


def example(rank, world_size):
    torch.manual_seed(0)
    torch.cuda.manual_seed(0)
    os.environ['MASTER_ADDR'] = 'localhost'
    os.environ['MASTER_PORT'] = '29500'
    # create default process group
    torch.cuda.set_device(rank)
    dist.init_process_group("nccl", rank=rank, world_size=world_size)

    # create local model 
    model = nn.Linear(2000, 2000).to(rank)

    # construct FSDP model
    ddp_model = FSDP(model, 
            flatten_parameters=True,
            # move_grads_to_cpu = True,
             move_params_to_cpu = True, 
             )

    # define loss function and optimizer
    loss_fn = nn.CrossEntropyLoss()
    optimizer = torch.optim.Adam(ddp_model.parameters(), lr=0.01)

    # forward pass
    outputs = ddp_model(torch.randn(1, 2000).to(rank))
    
    labels = torch.randn(1, 2000 ).to(rank)
    
    # backward pass
    loss = loss_fn(outputs, labels)
    print('开始loss')
    
    loss.backward()

    # update parameters
    optimizer.step()

def main():
    rank = int(os.environ["RANK"])
    world_size = int(os.environ["WORLD_SIZE"])
    example(rank,world_size)
    
if __name__=="__main__":
    main()
```
the run commad is  `python -m torch.distributed.launch --nproc_per_node 1 --use_env --standalone fsdp_gpu.py`

maybe somebody can answer me

**Comment by min-xu-ai** [comment]
The error msg should have been better. It really means that your model should be on cpu before it is passed to FSDP. It doesn’t mean FSDP code moves your model to cpu.

**Comment by xdd12135** [comment]
> The error msg should have been better. It really means that your model should be on cpu before it is passed to FSDP. It doesn’t mean FSDP code moves your model to cpu.

you mean if I want to set `move_params_to_CPU = True`, I should not use `model = model.to('cuda)` in my code, just keep model on CPU ,Am I right?

**Comment by min-xu-ai** [comment]
Yes. You are right
