### ISSUE TITLE
[Question] FSDP vs ZeRO

### ISSUE THREAD

**Issue by wookjeHan** [facebookresearch/fairscale#1090]
Hi.
First of all thanks for providing such a great library. I'm happy to use this library.

However, I am wondering the difference between ZeRO provided by DeepSpeed and FSDP.

Is there any noticeable difference?

Best Regards,
Wookje Han

**Comment by min-xu-ai** [comment]
Good question. I don't know any comprehensive comparison in terms of both APIs and performance. However, my impression is that deepspeed is a framework and FSDP is just a library that try to work like DDP in pytorch. If you have find any good comparison feel free to share it with us.
