### ISSUE TITLE
FSDP - Extra GPU memory consumption when maintaining a EMA weights

### ISSUE THREAD

**Issue by syorami** [facebookresearch/fairscale#1093]
I'm now training a large model with 2.5B parameters which consumes around 9G GPU memory. When maintaining EMA weights of total weights instead of sharded ones, the GPU memory increases by 2x (around 18G) instead of 1x. Here is my EMA implementation:

```
        model = runner.model
        if is_module_wrapper(model):
            model = model.module
        self.param_ema_buffer = {}
        if self.skip_buffers:
            self.model_parameters = dict(model.named_parameters())
        else:
            self.model_parameters = model.state_dict()
        for name, value in self.model_parameters.items():
            # "." is not allowed in module's buffer name
            buffer_name = f"ema_{name.replace('.', '_')}"
            self.param_ema_buffer[name] = buffer_name
            model.register_buffer(buffer_name, value.data.clone())
        self.model_buffers = dict(model.named_buffers())
        if self.checkpoint is not None:
            runner.resume(self.checkpoint)
```

After some hacking, I found that there are additional memory consumption (around 9G) in `alloc_storage_(p._full_param_padded, size=p_size)` when `_rebuild_full_params` in forward process compared with the memory consumption without EMA weights. I'm wondering where these consumptions come from. Thanks for any suggestions!

BTW, if I replace  `model.state_dict()` with `model.local_state_dict()` and only maintain sharded weights, everything works fine.

**Comment by min-xu-ai** [comment]
Maybe you don't keep to keep the reference of the full param tensors in self.model_parameters? model.state_dict all-gather all the params from all GPUs and keeps the full param tensors in p._full_param_padded. It should normally be related when you are done using it, but perhaps in your case, it is not released because of the references in self.model_parameters?

not sure I fully understand you code above, but hope my input helps regardless.

**Comment by min-xu-ai** [comment]
Please reopen if you have additional questions.

**Comment by syorami** [comment]
> Maybe you don't keep to keep the reference of the full param tensors in self.model_parameters? model.state_dict all-gather all the params from all GPUs and keeps the full param tensors in p._full_param_padded. It should normally be released when you are done using it, but perhaps in your case, it is not released because of the references in self.model_parameters?
> 
> not sure I fully understand you code above, but hope my input helps regardless.

Sry I missed the notification. I followed your suggestion and found that it is due to the `model.register_buffer(buffer_name, value.data.clone())` and this allocates additional storage for the registered buffers. However, simply keeping the `self.model_parameters` won't make any difference and I can constantly access the internal variables, which I though are supposed to be released as the training exceeds.

**Comment by min-xu-ai** [comment]
yeah, if you clone each tensor it will consume additional memory. once you call state_dict(), it should already allocate the full params and not freed since they are still referenced by self.model_parameters. Not sure if you have specific question for me. I hope things are working for you.

**Comment by syorami** [comment]
Nope. Thanks for your kindly explanation. It really helps.
