### ISSUE TITLE
Skip rather than fail tests in absence of `fair_dev`

### ISSUE THREAD

**Issue by h-vetinari** [facebookresearch/fairscale#1096]
Hey there

I help maintain many packages (including fairscale) in conda-forge. One regular part of the integration work is unvendoring things (so we don't carry a zillion redundant copies), switching to shared libraries wherever possible (same rationale), and so on.

To ensure that everything still runs as intended after eventual modifications, best practice is to run the test suite to ensure full functionality of the packaged binaries.

That is just what we have been doing, until our ability to run the tests got broken by the unconditional reliance of test code on `fair_dev`, in conjunction with the fact that it does not actually get installed.

As such, the [feedstock](https://github.com/conda-forge/fairscale-feedstock) has been stuck on 0.4.6 for about half a year.

I've flagged this in https://github.com/facebookresearch/fairscale/issues/1003, and while I'm grateful for the quick response in https://github.com/facebookresearch/fairscale/pull/1078, that PR only moved the package into a different namespace, but didn't fix either of:
* tests unconditionally relying on code in `fair_dev`
* `fair_dev` not installed by default (and I don't see an option to do so in `setup.py`)

I understand that `fair_dev` is supposed to be internal (see note in `fairscale.__init__.py`):
```
# NOTE: we don't maintain any public APIs in both experimental and fair_dev
#       sub-modules. Code in them are experimental or for developer only. They
#       can be changed, removed, anytime.
```

However, running tests of a given project _should not_ be developer-only, but something that regular users (and integrators!) are able to do themselves.

I even tried skipping tests with `fair_dev` in the string of the test serialization (using pytest's `-k "not fair_dev"`), but that only takes into account the names of the tests themselves (resp. the modules in which they are present), but not arbitrary code within them.

**Comment by min-xu-ai** [comment]
> fair_dev not installed by default (and I don't see an option to do so in setup.py)

Thanks for detailed bug report. I am sorry that I miss looked this. I am testing a fix now.

**Comment by min-xu-ai** [comment]
I just release 0.4.13. By testing myself, I see that fair_dev code is included in the release now. Can you try testing it again? Sorry for the trouble and I didn't know those code end up not being included.

**Comment by h-vetinari** [comment]
Thanks for the super quick response! Good news #1097 worked! 🥳 

It backported cleanly (together with #1078) back until [0.4.10](https://github.com/conda-forge/fairscale-feedstock/pull/23), so I've published the versions since then.

Thanks!
