### ISSUE TITLE
Lots of Commandline Output from this line.

### ISSUE THREAD

**Issue by jstraub** [facebookresearch/fairscale#1107]
https://github.com/facebookresearch/fairscale/blob/2350968ee61a6f9ca6ecd24aba9db536e814a24c/fairscale/internal/version.py#L27

this warning appears a LOT in the commandline output when training. Can we remove it or place it in a place where it gets only shown once at the start?

**Comment by min-xu-ai** [comment]
yeah, indeed. Will fix.
