### ISSUE TITLE
Combine powersgd with fairscale

### ISSUE THREAD

**Issue by amsword** [facebookresearch/fairscale#1113]
Does fairscale support to use PowerSGD to reduce the gradient size for low-bandwidth distributed training?

- Do not find the interface of register_comm_hook in this doc
https://fairscale.readthedocs.io/en/latest/api/nn/sharded_ddp.html?highlight=ShardedDataParallel

- powersgd hook from official pytorch doc
https://pytorch.org/docs/stable/ddp_comm_hooks.html#powersgd-communication-hook

**Comment by min-xu-ai** [comment]
the comm hook is DDP specific thing unfortunately. I would suggest to modify the sharded_ddp code directly and invoke the powersgd functions accordingly.
