### ISSUE TITLE
[AdaScale] self._hook() failure in __init__() of AdaScale() class

### ISSUE THREAD

**Issue by connieKing511** [facebookresearch/fairscale#1114]
When I use AdaScale, “self.optimizer = AdaScale(self.optimizer)” fails and this error is reported:
File "/.local/lib/python3.8/site-packages/fairscale/optim/adascale.py", line 198, in __init__
    self._hook()
  File "/.local/lib/python3.8/site-packages/fairscale/optim/adascale.py", line 210, in _hook
    h = param.register_hook(functools.partial(self._backward_hook, idx))
  File "/lib/python3.9/site-packages/torch/_tensor.py", line 524, in register_hook
    raise RuntimeError(
RuntimeError: cannot register a hook on a tensor that doesn't require gradient

My codes using AdaScale is as follows
```
use_adascale = True
if use_adascale:
        from fairscale.optim.adascale import AdaScale
        self.optimizer = AdaScale(self.optimizer)
```

What is the reason for this error? I would be very grateful if you could provide some help!

**Comment by min-xu-ai** [comment]
Interesting error. Maybe one of the params you have given to self.optimizer doesn't require gradient? Maybe you can filter that out? I.e. when you pass the set of parameters to self.optimizer, you can first check if p.requires_grad is True or not. If not, just remove it from the set of params passed to self.optimizer?

After that, I think this error would be gone.
