### ISSUE TITLE
Whether modifying the source code (fully_sharded_data_parallel.py) will bring safety hazard?

### ISSUE THREAD

**Issue by dropreg** [facebookresearch/fairscale#1115]
Hi，@min-xu-ai 
When I used fairscale to load the 7B model, I encountered the problem of insufficient GPU memory.
Then，I tried to fix this problem, I modified the function in the source code, and it work!

The File:  fairscale/nn/data_parallel/fully_sharded_data_parallel.py

The function：
``
line 1130-> def summon_full_params(self, recurse: bool = True, volatile: bool = False) -> Generator:
``

Before:
``
line 1173->  full_tensors = self._rebuild_full_params(force_full_precision=**True**)
``

After:
``
line 1173->  full_tensors = self._rebuild_full_params(force_full_precision=**False**)
``

I would like to ask whether this operation will bring some safety hazard when training the model later?

**Comment by min-xu-ai** [comment]
Do you have the full stacktrace before this function is called? It can be called in several different places (like loading checkpoints). Maybe in your case, you are loading it with full precision before and it wasn't needed? In that case, the change you made would be safe.

**Comment by dropreg** [comment]
> Do you have the full stacktrace before this function is called? It can be called in several different places (like loading checkpoints). Maybe in your case, you are loading it with full precision before and it wasn't needed? In that case, the change you made would be safe.

Thank you!!!
