### ISSUE TITLE
Hybrid Sharding in Fairscale's FSDP Implementation

### ISSUE THREAD

**Issue by stephanpeitz** [facebookresearch/fairscale#1133]
Hi all,

I just realised that `Hybrid Sharding` has been implemented in PyTorch's FSDP module.
What's the equivalent in Fairscale's FSDP implementation? 

`Hybrid Sharing` has been described here: https://arxiv.org/pdf/2304.11277.pdf (3.2.2)

Thanks for your help!

Cheers,
Stephan

**Comment by awgu** [comment]
I do not believe that it is supported in Fairscale FSDP, and Fairscale FSDP is no longer being actively developed. I am curious if there are any constraints against using PyTorch FSDP?

**Comment by stephanpeitz** [comment]
Hi Andrew, 

thanks for your quick reply!

>  I am curious if there are any constraints against using PyTorch FSDP?

Not at all, I think it's just convenience since FairSeq leverages FairScale. :) 

Cheers,
Stephan
