### ISSUE TITLE
torch.compile with FSDP

### ISSUE THREAD

**Issue by santha96** [facebookresearch/fairscale#1145]
Hi,
is it possible to use torch.compile with fsdp . if so , what is the right way and when to use torch.compile ?

**Comment by awgu** [comment]
`torch.compile` is not supported with Fairscale FSDP. There is preliminary support with PyTorch FSDP when passing `use_orig_params=True`, where the compute in each FSDP-wrapped module is compiled. More thorough support is under development.

**Comment by awgu** [comment]
I am marking this as closed because `torch.compile` support for Fairscale FSDP is not planned.
