### ISSUE TITLE
what are pointwise Optimizers and non-pointwise Optimizers?

### ISSUE THREAD

**Issue by bugm** [facebookresearch/fairscale#1170]
Hello, I recently read the doc about fairscale FSDP [EFFICIENT MEMORY MANAGEMENT](https://fairscale.readthedocs.io/en/stable/deep_dive/oss_sdp_fsdp.html)

Where it mentioned

4. Results should be identical to DDP with pointwise Optimizers, e.g., Adam, AdamW, Adadelta, Adamax, SGD, etc.. However, the sharding will result in slightly different results when using non-pointwise Optimizers, e.g., Adagrad, Adafactor, LAMB, etc.

I do understand how Adam and Adagrad working but I not not fully understand what cause the difference between pointwise Optimizers and non-pointwise Optimizers?

**Comment by awgu** [comment]
Pointwise optimizers means that the optimizer step can be defined per tensor element (i.e. per "point" in the tensor). Non-pointwise optimizers means that the optimizer step on a tensor element requires information from other tensor elements. For example, LAMB may compute some norm over the entire parameter tensor, which means that if shard the tensor across multiple GPUs, there is no way to compute that norm over the unsharded tensor without communication.

**Comment by bugm** [comment]
> Pointwise optimizers means that the optimizer step can be defined per tensor element (i.e. per "point" in the tensor). Non-pointwise optimizers means that the optimizer step on a tensor element requires information from other tensor elements. For example, LAMB may compute some norm over the entire parameter tensor, which means that if shard the tensor across multiple GPUs, there is no way to compute that norm over the unsharded tensor without communication.

Thanks for you answer. I have not used LAMB before and  I read some material about LAMB and understand what Non-pointwise optimizers means. Can you explain why Adagrad belongs to Non-pointwise optimizers? I did not see the Non-pointwise information in it.

**Comment by awgu** [comment]
As a guess, maybe the docs are referring to full matrix Adagrad (as opposed to the diagonal approximation, which is pointwise). From [here](https://optimization.cbe.cornell.edu/index.php?title=AdaGrad), the first equation is the full-matrix Adagrad, and the second equation is the diagonal Adagrad.

![Screenshot 2024-03-27 at 12 03 31 PM](https://github.com/facebookresearch/fairscale/assets/31054793/6c75da41-3bcf-4fec-8edb-222de88cdcd8)

The former having to compute the matrix inverse of $G_t^{1/2}$ may be the non-pointwise part.

**Comment by bugm** [comment]
> As a guess, maybe the docs are referring to full matrix Adagrad (as opposed to the diagonal approximation, which is pointwise). From [here](https://optimization.cbe.cornell.edu/index.php?title=AdaGrad), the first equation is the full-matrix Adagrad, and the second equation is the diagonal Adagrad.
> 
> ![Screenshot 2024-03-27 at 12 03 31 PM](https://private-user-images.githubusercontent.com/31054793/317346206-6c75da41-3bcf-4fec-8edb-222de88cdcd8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE3MDQ4NDYsIm5iZiI6MTcxMTcwNDU0NiwicGF0aCI6Ii8zMTA1NDc5My8zMTczNDYyMDYtNmM3NWRhNDEtM2JjZi00ZmVjLThlZGItMjIyZGU4OGNkY2Q4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI5VDA5MjkwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNlMTFjNjVmZmI2M2VjMDVlOWI5ODJlNzFkYzdkNjk3ZjIyNTI1YTBmOGRjNzE5MWQxN2I1MzNmYWQ3MzAzN2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KfW4j8hyNW7ESQ29quHu_lyal_35gazEbgAAqx9e93c)
> 
> The former having to compute the matrix inverse of Gt1/2 may be the non-pointwise part.

That make sense, thanks a lot!
