### ISSUE TITLE
Add mixed precision autocast to benchmarking script 

### ISSUE THREAD

**Issue by SeanNaren** [facebookresearch/fairscale#154]
## 🚀 Feature

It would be nice to make sure OSS/ShardedDDP plays nice with torch autocast! Adding it to the oss.py benchmark will allow us to ensure there is no glaring issues. I don't mind working on this!

## Motivation

Integrating OSS/ShardedDDP into PL :)

**Comment by min-xu-ai** [comment]
This seems like a unit test, not a benchmark?

For unit test, it would be nice to make sure we run a test only when its dependent files change in a PR or commit. But that is certainly outside and independent of this issue.

**Comment by SeanNaren** [comment]
I think we should have the functionality in both! I've been using the oss.py script primarily but should make its way into a unit test. What would you like the unit test to replicate/integrate into? was thinking this: https://github.com/facebookresearch/fairscale/blob/master/tests/nn/data_parallel/test_sharded_ddp.py

**Comment by SeanNaren** [comment]
Have a branch which is super simple, just adds autocast wrappers to the forward passes: https://github.com/SeanNaren/fairscale/tree/feature/autocast_benchmark

Once other functionality has merged, I'll open the PR :)

**Comment by blefaudeux** [comment]
The attached PR adds a benchmark option for that, and runs it on CI to make sure that we don't break it over time
