### ISSUE TITLE
benchmark test too tight?

### ISSUE THREAD

**Issue by min-xu-ai** [facebookresearch/fairscale#203]
Hi Ben,

Is the benchmark test too tight? I see this with my draft PR:

![image](https://user-images.githubusercontent.com/24926999/99861373-b6d63d00-2b4a-11eb-9d03-bfc228a3d458.png)

**Comment by blefaudeux** [comment]
hmm it's strange, I have not changed anything in that codebase for a while (the big PR is not merged). @msbaines recently had to dimnish the speed requisite when moving to torch 1.7, so there's definitely a downward trend not related to code changes, could be that it's tied to circleCI load balancing ? (aws I guess)

**Comment by msbaines** [comment]
The purpose of setting a tight threshold is to catch statistically significant regressions.

We check that the benchmark results are within 3 standard deviations of the reference mean. If the benchmark is failing, there is a high likelihood (>99%) that your change is causing a statistically significant performance regression (i.e. not in the noise).

If we are OK with the regression, then you can update the reference value based on new measurements. For example, I had to reduce the reference value when I update to PyTorch 1.7.0.

Overall, its fine to reduce the threshold if we are OK with the trade-off we are making. We just don't performance to drop unknowingly. We want to make conscious trade-offs.

**Comment by min-xu-ai** [comment]
I see. Thanks for explaining the 3 stddev. You can check my PR #202, which doesn't touch any of the files that could affect the benchmark AFAIK. I should have mentioned that in the first place. I agree we want to know whenever it drops. For this particular case, perhaps circleci machine is not fully deterministic in their performance?

**Comment by blefaudeux** [comment]
should be fixed by #204, closing
