### ISSUE TITLE
tutorial_pipe_multiprocess.py fails with pytorch 1.7

### ISSUE THREAD

**Issue by tchaton** [facebookresearch/fairscale#206]
## To Reproduce

Dear @froody,

I tried running the example `tutorial_pipe_multiprocess.py` with Pytorch 1.7 and I got this error:

<img width="1495" alt="Screenshot 2020-11-23 at 18 46 48" src="https://user-images.githubusercontent.com/12861981/100010710-93202a80-2dc8-11eb-9518-40781334ee6d.png">

1.
2.
3.

## Environment

Please copy and paste the output from the
environment collection script from PyTorch
(or fill out the checklist below manually).

You can run the script with:
```
# For security purposes, please check the contents of collect_env.py before running it.
python -m torch.utils.collect_env
```

 - PyTorch Version (e.g., 1.0):
 - OS (e.g., Linux):
 - How you installed PyTorch (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by froody** [comment]
Are you referring to the tensorpipe warning?

**Comment by froody** [comment]
Can you provide steps to reproduce? Is this on a branch? It looks from the backtrace like it involves pytorch-lightning, which isn't use by tutorial_pipe_multiprocess.py under normal conditions.

**Comment by tchaton** [comment]
Hey @froody,

You are right. I think it might be related to Lightning. Let me close this issue for now.

Best regards,
Thomas Chaton
