### ISSUE TITLE
project website has wrong urls for api docs

### ISSUE THREAD

**Issue by stas00** [facebookresearch/fairscale#208]
Half of your project website is 404

Looking like a configuration issue or wrong links. The pages are there, but urls are wrong.

https://fairscale.readthedocs.io/en/latest/ links to: https://fairscale.readthedocs.io/build/html/api/nn/pipe.html
but it should be https://fairscale.readthedocs.io/en/latest/api/nn/pipe.html instead.

same goes for all other api pages.

https://fairscale.readthedocs.io/en/latest/api/nn/model_parallel.html is the exception - it seems to need a separate page for each module under https://github.com/facebookresearch/fairscale/tree/master/fairscale/nn

**Comment by blefaudeux** [comment]
Many thanks for the report @stas00, configuration mistake indeed, we should have checked that.. Pushing a tentative fix in the coming days
