### ISSUE TITLE
[ShardedDDP] Replicate 'find_unused_parameters' feature

### ISSUE THREAD

**Issue by blefaudeux** [facebookresearch/fairscale#228]
## 🚀 Feature
Add an option to find unused parameters, either one shot (on first FW) or every FW. This would be required to enable bucketing

## Motivation
Bucketing (with or without tensor views) breaks when the model has unused parameters, because we're waiting for hooks which will never fire. A sane default is thus not to bucket, but it means that some perf is left on the table. A solution could be to add a setting (enum ?) to find unused parameters, either once or for every FW (more time consuming, may not make a lot of sense in that case), so that we don't wait for the corresponding hooks.

## Pitch
Trace the FW pass, check which parameters have been used. DDP already optionally does that, for similar reasons it seems 

## Alternatives
Never bucket, and rely on cuda single stream sync to make sure that reduce is done prior to optimizer stepping

## Additional context
cc @mrshenli @msbaines @min-xu-ai @seannaren

**Comment by min-xu-ai** [comment]
Nice. Do you think this will support activation checkpointing as well?

**Comment by blefaudeux** [comment]
I think so, at least it should be doable, with a context sync/manager ?

**Comment by min-xu-ai** [comment]
That's great. Current DDP does NOT work with checkpointing when find_unused_parameters is true though. I think that's related to bucketing. Some kind of test will be nice for this new feature.

**Comment by blefaudeux** [comment]
hmm, could be that I'm wrong in the above then. I would need to start digging into that before being sure, maybe that a second context manager could help for this specific usecase (aka: "stop tracing FW pass manager")

**Comment by min-xu-ai** [comment]
yeah, we basically use ddp.no_sync() today to workaround that issue when activation checkpointing is used.

**Comment by blefaudeux** [comment]
Hmm, thought popping up when discussing with @SeanNaren: how about using FW hooks to increment the counter, so that we wait for the actual number of requests ? that does not solve bucketing but it should work

**Comment by blefaudeux** [comment]
> Hmm, thought popping up when discussing with @SeanNaren: how about using FW hooks to increment the counter, so that we wait for the actual number of requests ? that does not solve bucketing but it should work

not possible on a per parameter basis, parameters only accept BW hooks.. not worth the effort at this point I think
