### ISSUE TITLE
[doc] instructions on how to install fairscale with pytorch-nightly

### ISSUE THREAD

**Issue by stas00** [facebookresearch/fairscale#250]
Well, I'm not sure where this tidbit could belong in your docs, but here is some useful info I have discovered:

If you're using pytorch-nightly installing `fairscale` will wipe the former out and install pytorch-1.7.1 or whatever the latest official version is instead, so you also want to add `--pre` and the channel the nightly came from, which tells pip to allow `pre-release` versions, and allows it to check that the right pytorch is installed already - so basically if you installed pytorch nightly with:

```
pip install --pre torch torchvision -f https://download.pytorch.org/whl/nightly/cu110/torch_nightly.html -U
```

and some time later when you come to build this project, you need to use the matching:

```
pip install  --pre  -f https://download.pytorch.org/whl/nightly/cu110/torch_nightly.html fairscale
```

(you may also need to add `--no-build-isolation`, see: https://github.com/facebookresearch/fairscale/pull/249)

I'm not sure where this could be documented in the `fairscale` project.

If you can't find any place to put this note in, we can just close this issue and it'll be self-documenting for those who seek out the answer - not sure if I used all the right words for google to match it.

**Comment by min-xu-ai** [comment]
I think with the latest fairscale that doesn't build cpp and doesn't have a build dep on pytorch, this issue is no longer there. Feel free to open if I shouldn't have closed.
