### ISSUE TITLE
[CI] Unit tests timing out randomly

### ISSUE THREAD

**Issue by blefaudeux** [facebookresearch/fairscale#275]
## 🐛 Bug
The CPU unit tests are becoming too slow for CircleCI, they randomly last over the 10min limitation and return a poor signal with unrelated failures

## Command
Checkout https://app.circleci.com/pipelines/github/facebookresearch/fairscale?branch=master

**Comment by min-xu-ai** [comment]
It seems that it is timing out here:
```
tests/nn/pipe_process/test_pipe.py::test_pipelined_backward[PipelineStyle.MultiProcess] PASSED [ 75%]
tests/nn/pipe_process/test_pipe.py::test_pipelined_backward[PipelineStyle.AsyncSchedule] PASSED [ 75%]
tests/nn/pipe_process/test_pipe.py::test_async_event_loop PASSED         [ 75%]
tests/nn/pipe_process/test_pipe.py::test_reuse_lazy 

Too long with no output (exceeded 10m0s): context deadline exceeded
```

The next good run only took 2min to finish for the whole 213 items. 

good: https://app.circleci.com/pipelines/github/facebookresearch/fairscale/1114/workflows/1992c86b-e028-4a13-934e-b71c0ccb92be/jobs/4700/parallel-runs/0/steps/0-111

bad: https://app.circleci.com/pipelines/github/facebookresearch/fairscale/1114/workflows/f3301cd7-18a0-458a-9649-99aad245cba2/jobs/4696/parallel-runs/0/steps/0-111

I don't see any obvious problem with the test in question.

**Comment by blefaudeux** [comment]
yeah, the thing is it does not seem to be always on the same test, see for instance https://app.circleci.com/pipelines/github/facebookresearch/fairscale/1118/workflows/2dd74077-8f62-4dbe-b4f3-0d6308b10b72/jobs/4718/parallel-runs/0/steps/0-111
I tried a faster execution through xdist, but it's not that, there must be a deadlock that I introduced recently when changing to file based init

**Comment by min-xu-ai** [comment]
perhaps there is a way to make pytest run tests in serial? then, you can loop it on a CPU machine until it timeout to see which test it is?

**Comment by blefaudeux** [comment]
> perhaps there is a way to make pytest run tests in serial? then, you can loop it on a CPU machine until it timeout to see which test it is?

it should already be serial by default, I tried to change the .join() to expose a hanging thread and it seemed to show that the issue was in a test which raised an exception on purpose, hence an hopeful fix
