### ISSUE TITLE
Saving/loading sharded checkpoints is failing

### ISSUE THREAD

**Issue by joshim5** [facebookresearch/fairscale#288]
## 🐛 Bug

I added the sharded DDP backend to Fairseq along with test coverage. Surprisingly, all unit tests I added to Fairseq and Fairscale are passing except for one -- a reproducibility test with RoBERTa (saving and loading checkpoints). I don't have this issue with a translation task using a fconv architecture.

I see the same thing with an interactive test from Myle with an NLP workload. Saving/reloading changes the numbers only after the first update, so it's likely something with the optimizer state.

Any idea of what might be up? Is there an edge case that would be reached only with transformers and not fconv?

Here's [the relevant Fairseq PR](https://github.com/fairinternal/fairseq-py/pull/1531) that adds:
- sharded DDP engine
- rework clip norm for OSS (master gives incorrect clip norms)
- support model parallelism clip norm in OSS
- tests

## To Reproduce

1. Clone fairseq from the branch `protein-sharded-ddp` on [this Fairseq PR](https://github.com/fairinternal/fairseq-py/pull/1531).
2. Move to the `model-parallel-oss` branch on fairscale
3. `python -m unittest -v tests.test_reproducibility.TestReproducibility.test_reproducibility_oss_sharded_ddp_masked_lm` should fail.

You will see a message similar to this:
```
======================================================================
FAIL: test_reproducibility_oss_sharded_ddp_masked_lm (__main__.TestReproducibility)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/test_reproducibility.py", line 153, in test_reproducibility_oss_sharded_ddp_masked_lm
    train_fn=test_roberta_masked_lm,
  File "tests/test_reproducibility.py", line 91, in _test_reproducibility
    self.assertAlmostEqual(catch_null(train_log[k]), catch_null(train_res_log[k]), delta=delta)
AssertionError: 4.03 != 3.964 within 0.0001 delta

----------------------------------------------------------------------
Ran 1 test in 81.771s

FAILED (failures=1)
```

## Expected behavior

The test should pass.

## Additional context
The test `test_reproducibility_oss_sharded_ddp_masked_lm` trains a Masked LM RoBERTa model for a few steps; saves an intermediate checkpoint; and trains a new model from the intermediate checkpoint. It asserts that the training logs of the two trajectories match exactly.

The following Fairseq tests pass:
1. `test_reproducibility_oss_sharded_ddp`: Same as above, but use a fconv architecture with a translation task.
2. `test_reproducibility_oss`: Same as (1), but uses c10d ddp backend.
3. `TestSharded. test_sharding`: Trains two identical models. One is sharded; one is not. Confirms that losses and grad norms are the same in a training trajectory.
4. `TestSharded.test_saving`: Same as (3) but with a few additional cases where the sharded model is saved along the way.

Additionally, the Fairscale tests I added also pass.  Taken together, I highly suspect that there is an edge case that is missing in the current test coverage that could help explain the discrepancy with masked LM models.

## Environment

Please copy and paste the output from the
environment collection script from PyTorch
(or fill out the checklist below manually).

You can run the script with:
```
Collecting environment information...
PyTorch version: 1.5.0a0+4ff3872
Is debug build: No
CUDA used to build PyTorch: 10.1

OS: Ubuntu 20.04.1 LTS
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
CMake version: version 3.16.3

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration:
GPU 0: Tesla V100-SXM2-32GB
GPU 1: Tesla V100-SXM2-32GB
GPU 2: Tesla V100-SXM2-32GB
GPU 3: Tesla V100-SXM2-32GB
GPU 4: Tesla V100-SXM2-32GB
GPU 5: Tesla V100-SXM2-32GB
GPU 6: Tesla V100-SXM2-32GB
GPU 7: Tesla V100-SXM2-32GB

Nvidia driver version: 450.80.02
cuDNN version: Could not collect

Versions of relevant libraries:
[pip] msgpack-numpy==0.4.5
[pip] numpy==1.18.3
[pip] numpydoc==0.9.2
[pip] pytorch-lightning==0.8.1
[pip] pytorch-pretrained-bert==0.6.2
[pip] pytorch-transformers==1.1.0
[pip] torch==1.5.0a0+4ff3872
[pip] torch-blocksparse==1.1.1
[conda] blas                      1.0                         mkl
[conda] libblas                   3.8.0                    15_mkl    conda-forge
[conda] libcblas                  3.8.0                    15_mkl    conda-forge
[conda] liblapack                 3.8.0                    15_mkl    conda-forge
[conda] magma-cuda101             2.5.2                         1    pytorch
[conda] mkl                       2020.1                      217
[conda] mkl-include               2020.0                      166
[conda] mkl-service               2.3.0            py36he904b0f_0
[conda] mkl_fft                   1.0.15           py36ha843d7b_0
[conda] mkl_random                1.1.0            py36hd6b4f25_0
[conda] pytorch-lightning         0.8.1                    pypi_0    pypi
[conda] pytorch-pretrained-bert   0.6.2                    pypi_0    pypi
[conda] pytorch-transformers      1.1.0                    pypi_0    pypi
[conda] torch                     1.5.0a0+4ff3872          pypi_0    pypi
[conda] torch-blocksparse         1.1.1                    pypi_0    pypi
```

**Comment by blefaudeux** [comment]
Thanks for the report Joshua, looking into that asap !

**Comment by blefaudeux** [comment]
@joshim5 could you elaborate on "master gives incorrect clip norms" for OSS ?

**Comment by blefaudeux** [comment]
> @joshim5 could you elaborate on "master gives incorrect clip norms" for OSS ?

ah no ok, this is because of model parallel, current OSS is explicitly not model parallel compatible with respect to clip grad norms

**Comment by joshim5** [comment]
Hey @blefaudeux -- no, that's not what I meant. Current Fairseq does not use the clip grad norm function from Fairscale. It uses the Fairseq clip norm functions which do not contain any logic around the sharding. The model trains correctly, but the reported clip norms are incorrect. 

I fixed this by having Fairseq use the optimizer's clip grad norm function if that attribute exists on the optimizer.

**Comment by blefaudeux** [comment]
@joshim5 isn't this because of not consolidating the state in the first place ? It's an issue with the current API, I would love to move to RPC and remote references because of that, but it would take more time (and require that RPC is initialized before use)

**Comment by blefaudeux** [comment]
discussed 1:1, but it looks like the optimizer is not fed with the same data for the second unit test, which would explain why the results differ. One explanation could be that in the second unit test the model is not restored properly, but that's outside of OSS' scope

**Comment by blefaudeux** [comment]
Closing the issue, not tied to fairscale if I got this correctly. Feel free to reopen @joshim5 if need be
