### ISSUE TITLE
moe test failed on CPU

### ISSUE THREAD

**Issue by min-xu-ai** [facebookresearch/fairscale#336]
## 🐛 Bug

See here: https://app.circleci.com/pipelines/github/facebookresearch/fairscale/1413/workflows/373f63b0-9e45-4925-93ba-be44b48ce1df/jobs/6354

moe test failed on CPU

I don't have mpi on my machine yet to reproduce it. @msbaines @blefaudeux @anj-s, have you seen it before?

**Comment by anj-s** [comment]
@min-xu-ai I've seen the MOE tests fail before but it was locally so I assumed I did not have the right configs in place.

**Comment by min-xu-ai** [comment]
I think something is still fishy. I have MPI installed on my machine now, but this doesn't reproduce.

**Comment by msbaines** [comment]
I looked at testing on master and have not seen this failure in the last 20 runs.
