### ISSUE TITLE
should we avoid depending on torchvision?

### ISSUE THREAD

**Issue by min-xu-ai** [facebookresearch/fairscale#340]
As I was working on this PR. I found that torchvision upstream is not always sync'ed well with torch.

https://github.com/facebookresearch/fairscale/blob/dbdf6586b5e07e41b49b6dcc6c65e11e8458cc17/.circleci/config.yml#L93

Should we remove our dependency on torchvison? It seems we only needed a model from it, which we can just import it with the benefit of the model will stay the same. What do we miss if we do that?

**Comment by Vittorio-Caggiano** [comment]
we might need to load datasets for [examples](https://github.com/facebookresearch/fairscale/blob/65ca68a96850dc362098743aca9f0dcd3a1c3203/examples/mnist_test_pipe.py#L12 ) and/or benchmarks e.g.  what do you think @anj-s ?

**Comment by min-xu-ai** [comment]
good point. it depends on also where do we position fairscale. torchvision is on top of torch, so is fairscale. In a block diagram of different libraries, should fairscale be on top of torchvision?

**Comment by blefaudeux** [comment]
it's not a real dependency, it's only here for the benchmarks to pull in a standard model that people in CV expect to work, I don't think that should be part of any diagram.

**Comment by min-xu-ai** [comment]
well, it is in requirements-test.txt. Should we move it into a separate requirements.txt? For now, it causes an issue when I am trying to using py39, which needs torch 1.8, but then torchvision doesn't yet work with py39.

**Comment by blefaudeux** [comment]
> well, it is in requirements-test.txt. Should we move it into a separate requirements.txt? For now, it causes an issue when I am trying to using py39, which needs torch 1.8, but then torchvision doesn't yet work with py39.

well, it's a requirements for tests, it is not a requirement for the fairscale library, so it kind of makes sense I think ? My point above is that it's *not* a requirement for fairscale, and that a graph where fairscale sits on top of torchvision would not make sense.

Now if python3.9 is a priority it could be removed from the requirements-test file, and imported "by hand" for all the benchmarks jobs, or we could have yet another requirements file, no big opinion there

**Comment by min-xu-ai** [comment]
Sure, sounds reasonable. Nothing need to be done for now then.
