### ISSUE TITLE
CHANGELOG url don't appear.

### ISSUE THREAD

**Issue by tchaton** [facebookresearch/fairscale#396]
## To Reproduce

1.
2.
3.

Dear people from Fairscale,

I have seen the CHANGELOG display numbers as #386, but not urls. It would be helpful if this was updated :)
Personally, I find PRs url more helpful than issues, as we can directly jump in the code. 

Best,
Thomas Chaton.

## Environment

Please copy and paste the output from the
environment collection script from PyTorch
(or fill out the checklist below manually).

You can run the script with:
```
# For security purposes, please check the contents of collect_env.py before running it.
python -m torch.utils.collect_env
```

 - PyTorch Version (e.g., 1.0):
 - OS (e.g., Linux):
 - How you installed PyTorch (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by blefaudeux** [comment]
yop, fair enough, will do
