### ISSUE TITLE
pip install giving error

### ISSUE THREAD

**Issue by VirajBagal** [facebookresearch/fairscale#407]
I am trying to install fairscale. But I am getting the following issue when I do 

```python
pip install fairscale
```

> Defaulting to user installation because normal site-packages is not writeable
> ERROR: Could not find a version that satisfies the requirement fairscale (from versions: none)
> ERROR: No matching distribution found for fairscale

I have torch version 1.7.1

**Comment by blefaudeux** [comment]
![Screenshot from 2021-02-20 08-24-50](https://user-images.githubusercontent.com/3072861/108602119-20860300-7355-11eb-9631-086583c4f2e8.png)
I just tested in a disposable (empty) conda env, and it seems to work fine ? could you explain the context a bit more ?

**Comment by blefaudeux** [comment]
guessing that this was a local issue and not getting any more context, closing that. Feel free to reopen with more information
