### ISSUE TITLE
[tests] Ampnet unit test fails

### ISSUE THREAD

**Issue by anj-s** [facebookresearch/fairscale#426]
## 🐛 Bug

Ampnet unit test - tests/experimental/nn/ampnet_pipe_process/test_ampnet_pipe.py::test_async_event_loop_interleave_simple fails due to error. We were not running the unit tests and [PR](https://github.com/facebookresearch/fairscale/pull/419) attempts to restart the tests again. 
Stack trace:https://app.circleci.com/pipelines/github/facebookresearch/fairscale/1782/workflows/4573c633-dde6-4fe8-9224-ca1d009772df/jobs/8949/steps

Skipping the test right now to unblock the PR. We should reenable once we figure out the fix.

## To Reproduce

1. pytest fairscale/experimental/tests/nn/ampnet_pipe_process/test_ampnet_pipe.py

## Environment

Please copy and paste the output from the
environment collection script from PyTorch
(or fill out the checklist below manually).

You can run the script with:
```
# For security purposes, please check the contents of collect_env.py before running it.
python -m torch.utils.collect_env
```

 - PyTorch Version (e.g., 1.0):
 - OS (e.g., Linux):
 - How you installed PyTorch (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by min-xu-ai** [comment]
cc @sidgoyal78 ?

**Comment by sidgoyal78** [comment]
I missed this, let me take a look. Thanks for tagging @min-xu-ai  :)

**Comment by anj-s** [comment]
Thanks @min-xu-ai for tagging and @sidgoyal78 for taking a look! Assigning this to you for now.
