### ISSUE TITLE
[FSDP] improve robustness to mismatch between torch.cuda.current_device and model's device

### ISSUE THREAD

**Issue by myleott** [facebookresearch/fairscale#444]
## 🚀 Feature

Currently we require the user to set the current CUDA device appropriately when using FSDP, e.g.:
```python
torch.cuda.set_device(device)
model = FSDP(model, ...).cuda()
```

PyTorch DDP is more robust to this, see this example: https://github.com/facebookresearch/fairscale/issues/423#issuecomment-784633275

We currently use `.cuda()` and `torch.device("cuda")` in a few places, we can add a new `compute_device` arg and use that instead.

**Comment by min-xu-ai** [comment]
I can take this one. However, when cpu offload is used, param's device won't help, right? We still need torch.cuda.set_device(), right? Just want to confirm my understanding here.

**Comment by myleott** [comment]
Yeah, in that case maybe we can let the user pass a `compute_device` option explicitly?
