### ISSUE TITLE
[benchmarks] Add support for running experimental/ampnet benchmarks

### ISSUE THREAD

**Issue by anj-s** [facebookresearch/fairscale#462]
We should add [benchmarks/experimental/ampnet.py](https://github.com/facebookresearch/fairscale/blob/master/benchmarks/experimental/experimental_ampnet.py) to our circleCI config so that we are testing performance on a regular basis.

@msbaines @sidgoyal78 Let me know if this makes sense. Please feel free to close if this is not something we want to track. Thanks!

**Comment by sidgoyal78** [comment]
I'd more inclined towards supporting the unit tests https://github.com/facebookresearch/fairscale/issues/426 for now. This benchmark is a preliminary one and we should probably wait for more benchmarking to make a call.
