### ISSUE TITLE
[dev] should we support import *?

### ISSUE THREAD

**Issue by min-xu-ai** [facebookresearch/fairscale#471]
During this code review, this question came up. Thanks to @msbaines !

https://github.com/facebookresearch/fairscale/pull/467#discussion_r587572010

The question is around whether we should support `import *` by maintaining `__all__` in the `__init__.py` file.

cc: @anj-s @blefaudeux

**Comment by min-xu-ai** [comment]
I am leaning toward not support it, i.e. don't maintain an `__all__` in the init file. Here are 3 reasons:

1. it is slower for development: developer need to maintain the list and potentially sort it. If it gets long, duplicates and typos can happen. Reviewers need to check it too.
2. when `import *` is used, it is harder to figure out where a symbol comes from. Say:
```
from x import *  # imported foo, bar

...
foo()
bar()
```

In the file above, it is hard to search the file and figure out where foo and bar comes from.

3. it can mask bugs:
```
from x import *   # imported foo

def foo():  # masked foo. ---> later, this function is removed
  ...

...
# use of foo
v = foo()
```

Now if local foo is removed, it is not easy to get a undefined symbol error since the imported foo can take over. That can mask bugs that's harder to find.

So, I propose:

1. remove all `__all__` from init files
2. update CONTRIBUTE.md to state this explicitly.

what do you think?

**Comment by blefaudeux** [comment]
no strong opinion, I've had this thought a couple of times when doing "import *" and feeling "oh, this feels a bit dangerous". In many languages this is typically bad practice, because of the shadowing that you've mentioned. If it was not for hypothetical backward compatibility concerns (not sure how big of an issue that is), I would also lean towards removing it

**Comment by msbaines** [comment]
> I am leaning toward not support it, i.e. don't maintain an `__all__` in the init file. Here are 3 reasons:
> 
> 1. it is slower for development: developer need to maintain the list and potentially sort it. If it gets long, duplicates and typos can happen. Reviewers need to check it too.
> 2. when `import *` is used, it is harder to figure out where a symbol comes from. Say:
> 
> ```
> from x import *  # imported foo, bar
> 
> ...
> foo()
> bar()
> ```
> 
> In the file above, it is hard to search the file and figure out where foo and bar comes from.
> 
> 1. it can mask bugs:
> 
> ```
> from x import *   # imported foo
> 
> def foo():  # masked foo. ---> later, this function is removed
>   ...
> 
> ...
> # use of foo
> v = foo()
> ```
> 
> Now if local foo is removed, it is not easy to get a undefined symbol error since the imported foo can take over. That can mask bugs that's harder to find.
> 
> So, I propose:
> 
> 1. remove all `__all__` from init files
> 2. update CONTRIBUTE.md to state this explicitly.
> 
> what do you think?

If you remove `__all__` from `__init__.py` files you get the default behavior which is worse. So we could have an empty `__all__` or supports symbols that make sense. Supporting it is useful when using the library interactively via a repl or notebook. I think we should have an `__all__` in every `__init__.py` but should carefully add symbols when it makes sense. By default it should be empty.

**Comment by min-xu-ai** [comment]
Empty `__all__` is good too. Can you provide more details on what should be the guideline on putting symbols in `__all__`?

**Comment by msbaines** [comment]
> If __all__ is not defined, the statement from sound.effects import * does not import all submodules from the package sound.effects into the current namespace; it only ensures that the package sound.effects has been imported (possibly running any initialization code in __init__.py) and then imports whatever names are defined in the package. This includes any names defined (and submodules explicitly loaded) by __init__.py. It also includes any submodules of the package that were explicitly loaded by previous import statements.

https://docs.python.org/3/tutorial/modules.html#importing-from-a-package

I think every file having an empty __all__ is fine. We may late want to revise to allow support for adding symbols when they are useful for repl and notebook.

**Comment by min-xu-ai** [comment]
My reading of that paragraph is that `__all__` still only affects `import *`. Perhaps I should do some experiments. @colesbury, any insights?

**Comment by msbaines** [comment]
> My reading of that paragraph is that `__all__` still only affects `import *`. Perhaps I should do some experiments. @colesbury, any insights?

The paragraph is describing what happens when `__all__` is not defined.

**Comment by min-xu-ai** [comment]
here is some testing:

```
m1n@m1n-mbp temp % find t
t
t/__init__.py
t/foo.py
m1n@m1n-mbp temp % cat t/__init__.py
from .foo import bar

#__all__ = []
m1n@m1n-mbp temp % cat t/foo.py
class bar:
  pass
```

with `__all__` above commented out:
```
m1n@m1n-mbp temp % python -c "from t import *; print(globals())"
{'bar': <class t.foo.bar at 0x1071d5a78>, '__builtins__': <module '__builtin__' (built-in)>, '__package__': None, '__name__': '__main__', 'foo': <module 't.foo' from 't/foo.pyc'>, '__doc__': None}
```

If `__all__` is define as empty:
```
m1n@m1n-mbp temp % python -c "from t import *; print(globals())"
{'__builtins__': <module '__builtin__' (built-in)>, '__name__': '__main__', '__doc__': None, '__package__': None}
```

I think this shows that if we have `__all__` define as empty then `import *` won't import anything. Let's go with that or not? @msbaines @blefaudeux @anj-s
