### ISSUE TITLE
Using  torch.distributed.launch with ShardedDDP

### ISSUE THREAD

**Issue by jesus-villalba** [facebookresearch/fairscale#477]
Hi,
The tutorial about optimizer state sharding with dataparallel, 
https://fairscale.readthedocs.io/en/latest/tutorials/oss.html
it mentions that children processes should be created with the multiprocessing.spawn utility
```
mp.spawn(
        train,
        args=(WORLD_SIZE, EPOCHS),
        nprocs=WORLD_SIZE,
        join=True
    )
```
Is there any reason why we cannot use the launch utility?:
```
python -m torch.distributed.launch
```
My issue here is that when using mp.spawn, the dataloader workers are created using 'spawn' mode, and copies of the dataset are serialized to the child processes. Then, it fails if the dataset class has some variable that is not serializable, for example if you have a file variable.
Meanwhile, torch.distributed.launch creates child processes with fork mode and doesn't require serialization

Thanks

**Comment by blefaudeux** [comment]
Hi Jesus, thanks for the question ! You can use any launcher you prefer, there's no hard dependency on either of them, each ShardedDDP just ideally lives in a seperate process and has access to seperate GPUs, that's all

**Comment by blefaudeux** [comment]
closing the issue, feel free to re-open if you face some problems

**Comment by blefaudeux** [comment]
re-opening the issue, the tutorial should be fixed, the wording is not good indeed

**Comment by jesus-villalba** [comment]
Thank you for your prompt reply
