### ISSUE TITLE
update to pytorch 1.8

### ISSUE THREAD

**Issue by min-xu-ai** [facebookresearch/fairscale#481]
1.8 is released. should be update to it and retire the support of 1.5?

cc: @blefaudeux @msbaines @anj-s

**Comment by blefaudeux** [comment]
Oh yes please ! Best news of the day

**Comment by min-xu-ai** [comment]
I don't have any cycle immediately. Maybe someone can first replace the 1.8 nightly in the CI config file? I don't think this is urgent though. perhaps pip install issue is more urgent. :)

**Comment by blefaudeux** [comment]
thanks Mandeep for this !

**Comment by min-xu-ai** [comment]
Yes, thank you so much, Mandeep!
