### ISSUE TITLE
[FSDP] flatten param and optimizer

### ISSUE THREAD

**Issue by min-xu-ai** [facebookresearch/fairscale#492]
cc @prigoyal @myleott 

In VISSL, we have this function that collect different parameters from the model and group them into different parameter groups.

https://github.com/facebookresearch/vissl/blob/48b2984111c474a0da63c9c228b10281a0dbe737/vissl/optimizers/optimizer_helper.py#L102

However, when FSDP flatten the param, the original parameters accessed above in the function are not really backed by any storage when that function is run. When that function returns those parameter groups to an optimizer, the torch optimizer.py assert that the parameters do not have `is_leaf` flag set.

**Comment by myleott** [comment]
Yep, with flattening then all the module attributes become views into a single flat nn.Parameter, so it’s not really possible to divide their optimization params like this.

This will be a bit tricky to support, but a couple options:
1) we can try to reimplement FlattenParamsWrapper to replace each params’s storage (making them point to a portion of the flat param) without actually replacing the attributes with views.
2) we can add all-gather bucketing and tune it to close the huge perf gap when not using flattening.

**Comment by min-xu-ai** [comment]
This is replaced and being worked on in #697. Hence, closing this a dup.
