### ISSUE TITLE
[benchmarks] consistency of license header in scripts

### ISSUE THREAD

**Issue by sidgoyal78** [facebookresearch/fairscale#506]
Several scripts in benchmarks (`benchmarks/**/*.py`) have a single line FB header
```
# Copyright (c) Facebook, Inc. and its affiliates. All rights reserved.
```

We should add these 2 license statements as well:
```
# This source code is licensed under the BSD license found in the
# LICENSE file in the root directory of this source tree.
```

**Comment by anj-s** [comment]
Thanks for opening this! I noticed this too in one of my PRs. Happy to add it to all the files if you want to assign this issue to me.
