### ISSUE TITLE
modify moe mpi tests to use multiprocessing and nccl instead

### ISSUE THREAD

**Issue by msbaines** [facebookresearch/fairscale#548]
## 🚀 Feature
We would like for all moe tests to be converted from mpi to nccl+multiprocessing

## Motivation

Now that all_to_all is supported by PyTorch 1.8.0. We'd like to convert these tests to use NCCL.

## Pitch

Currently these tests are CPU tests. By migrating to NCCL they would become GPU tests.

**Comment by tani18dr** [comment]
It would be nice if FastMoE is also compatible.
https://arxiv.org/pdf/2103.13262.pdf
https://github.com/laekov/fastmoe
