### ISSUE TITLE
FSDP: named_parameter return value

### ISSUE THREAD

**Issue by min-xu-ai** [facebookresearch/fairscale#569]
Some pytorch code that use named_parameter's return values to match layer's name and perform operations on it. FSDP returns them differently (in terms of the name) than unwrapped module. It would be nice to return the original names.

@myleott @sshleifer, do you see any downside of doing this? Should I keep it an option to return the wrapped names?

**Comment by sshleifer** [comment]
Is this separate from [`FlattenParamsWrapper`](https://github.com/facebookresearch/fairscale/blob/master/fairscale/nn/misc/flatten_params_wrapper.py#L249)? 
It would definitely be nice to return the original names!

**Comment by min-xu-ai** [comment]
> Is this separate from [`FlattenParamsWrapper`](https://github.com/facebookresearch/fairscale/blob/master/fairscale/nn/misc/flatten_params_wrapper.py#L249)?

Yeah, this is different `state_dict` API. This is for `named_parameters`. I think it would affect both FSDP and FlattenParamsWrapper.

> It would definitely be nice to return the original names!

Thanks for confirming!
