### ISSUE TITLE
[FSDP] The rightway to use cpu_offload?

### ISSUE THREAD

**Issue by BIGBALLON** [facebookresearch/fairscale#571]
## ❓ Questions and Help

I'm trying to use FSDP for efficient memory saving,  but I got the following errors, I'm confused what is the right way to use ``cpu_offload``:

``` bash
    # net = DDP(net, device_ids=[local_rank], output_device=local_rank)           ---- works fine
    # net = FullyShardedDataParallel(net, mixed_precision=True, cpu_offload=False)   ---- works fine 
    net = FullyShardedDataParallel(net, mixed_precision=True, cpu_offload=True)        ---- get the error
```

``` bash
ully_sharded_data_parallel.py", line 636, in _lazy_init
    self._init_param_attributes(p)
  File "/home/developer/miniconda/envs/pth17/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 26, in decorate_context
    return func(*args, **kwargs)
  File "/home/developer/miniconda/envs/pth17/lib/python3.7/site-packages/fairscale/nn/data_parallel/fully_sharded_data_parallel.py", line 698, in _init_param_attributes
    assert p._fp32_shard.device == torch.device("cpu")
AssertionError
```

**Comment by min-xu-ai** [comment]
Hi there, did you place your model on CPU device first? With cpu_offload=True, I think you need the model to start on the CPU device. See how it is used in the test here:

https://github.com/facebookresearch/fairscale/blob/5a3df0da20ac446ba7aab31086c128e26595683c/tests/nn/data_parallel/test_fsdp.py#L287

note `use_cuda=False` there.

**Comment by BIGBALLON** [comment]
Hi @min-xu-ai, 

https://github.com/facebookresearch/fairscale/blob/5a3df0da20ac446ba7aab31086c128e26595683c/tests/nn/data_parallel/test_fsdp.py#L104

**Comment by BIGBALLON** [comment]
Hi, @min-xu-ai, thanks for your answer, I get the point.

> cpu_offload needs the model to start on the CPU device

**Comment by HUIZ-A** [comment]
I'm still confusing that if I wanna FSDP the model on different GPUs, how could I make it on my CPU?
