### ISSUE TITLE
FSDP: Consolidate cpu_adam optimizer state dict

### ISSUE THREAD

**Issue by sshleifer** [facebookresearch/fairscale#602]
### Possible Approaches
1. document that cpu optimizers will break all gather and don't fix
1. cast to cuda before `all_gather`
1. ~learn to communicate CPU tensors over a NCCL process group~ (not possible.)
1. make a new `mpi/gloo` process group on the fly.

**Comment by myleott** [comment]
2. could be reasonable, and is how we handle `apply()` when the model is still on CPU:
```python
model = Net()   # leave on CPU
fsdp_model = FSDP(model)
fsdp_model.apply(my_weight_init_fn)  # this will move shard to cuda, all-gather then call my_weight_init_fn
```
