### ISSUE TITLE
[FSDP] mixed_precision 

### ISSUE THREAD

**Issue by BIGBALLON** [facebookresearch/fairscale#604]
## ❓ Questions and Help

from the FSDP [tips](https://fairscale.readthedocs.io/en/latest/api/nn/fsdp_tips.html)

```
If you’re using torch.cuda.amp.autocast for mixed-precision, 
that’s fully compatible with the FSDP wrapper, 
just set mixed_precision=True
```

``mixed_precision`` is compatible with ``torch.cuda.amp.autocast``, I have another question:

If ``torch.cuda.amp.autocast`` is not used,
can ``mixed_precision=True`` still work normally since we not use ``GradScaler`` ?
thanks a lot

**Comment by min-xu-ai** [comment]
I don't think so. See test test_fsdp_regnet.py. I think it will depend on layers. Some layers won't be happy with FSDP's mixed_precision=True without autocast.

**Comment by min-xu-ai** [comment]
Also, sharded grad scaler is needed afaik

**Comment by min-xu-ai** [comment]
please reopen if you have more questions. totally fine. closing for now.

**Comment by BIGBALLON** [comment]
@min-xu-ai I got the point, thanks a lot!

**Comment by syorami** [comment]
> I don't think so. See test test_fsdp_regnet.py. I think it will depend on layers. Some layers won't be happy with FSDP's mixed_precision=True without autocast.

hi @min-xu-ai do those "some layers" include norm layers such as layernorm? I found the parameters in layernorm are also cast to fp16. This could result numerical precision problems and I'm wondering whether it's related with my loss disconvergence.

**Comment by min-xu-ai** [comment]
Yes, it is possible. But I don't have first hand experience on layer norm particularly for mixed precision.
