### ISSUE TITLE
[FSDP] Expose the named_shards_parameters when using flatten_params=True

### ISSUE THREAD

**Issue by prigoyal** [facebookresearch/fairscale#644]
The goal is to be able to get information about original parameters. This needs to be handled carefully in FSDP:

FSDP sharding should incorporate the "view" into the sharding and share the final metadata keeping in mind a) flattening or not b) padding or not

When we construct the `optimizer = nn.SGD(model.parameters(), ...)` we should call `optimizer = nn.SGD(model.named_shards_parameters(), ....)` instead.

**Comment by min-xu-ai** [comment]
We can close this since we have both #696 and #697?
