### ISSUE TITLE
[ShardedDDP] Expose 'module' property from ShardedDDP

### ISSUE THREAD

**Issue by apsdehal** [facebookresearch/fairscale#646]
## 🚀 Feature

Expose `module` property from ShardedDDP again which points to underlying wrapped model.

## Motivation

Recent PR #611 made a lot of class members in ShardedDDP private. Unfortunately, this behavior is now different from DDP which exposes module property to expose the underlying model directly. In MMF's checkpointing system, we use this property to extract out the underlying model to allow checkpoints to work agnostic of distributed system or not. 

## Pitch

I can open up a PR to expose it as a property if possible.

## Alternatives

I can hack around in our code to check `_module` but the change in itself is backwards incompatible from at least 3.3 to 3.6 version of fairscale.

**Comment by blefaudeux** [comment]
ah crap, there was a unit test on that, how did this slip through :/ Thanks for the report @apsdehal , fixing that ASAP

**Comment by blefaudeux** [comment]
let me know if you face any issues @apsdehal, this auto closed because the issue was linked, I believe that should be fine by now
