### ISSUE TITLE
[auto_wrap] Supporting multiple auto_wrap

### ISSUE THREAD

**Issue by QuentinDuval** [facebookresearch/fairscale#649]
### Context

In the context of VISSL, we are interested in calling `auto_wrap_bn` to deal with the Synchronized Batch Normalization layers and then call `auto_wrap` to automatically wrap some other layers (such as big layers by using a policy like `default_auto_wrap_policy`).

However, the following assertion in `auto_wrap.py` prevents us from doing so:

```
# Make sure no child is not already wrapped.
for _, child in module.named_modules():
    assert not isinstance(child, cast(type, ConfigAutoWrap.wrapper_cls))
```

This assertion seems necessary considering what follows in the code:

```
# We count all params, assuming none of them is already wrapped.
num_params = sum([p.numel() for p in module.parameters()])
```

But in the case of `auto_wrap_bn`, it is not necessary (since the BN will not be shared).

### Workaround

My original idea was to work-around that is to write my own policy that combines `auto_wrap_bn` and the subsequent `auto_wrap` but this is cumbersome:
- I end up not directly using a very useful feature of fairscale
- Since I want different parameters for FSDP for BN and other layers, I will have to hack a bit to make it work

I found another way to circumvent the assertion in my case, by using this hack:

```
class _FSDP_WRAPPER:
    def __new__(cls, module, **kwargs):
        return FSDP(module, **kwargs)

with enable_wrap(auto_wrap_policy=_policy, wrapper_cls=_FSDP_WRAPPER, **fsdp_config):
        return auto_wrap(module)
```

This allows me to avoid the check completely, by using `__new__` to return a `FSDP` wrapper hidden behind another class. 

Nifty, it works, but is there any better solution available to me? (avoiding such hacks)

## Interested parties

CC: @min-xu-ai @prigoyal

**Comment by min-xu-ai** [comment]
I think the assert was probably not a good idea. It seems that it should only be asserted when num_param based wrapper policy is being used. But it asserts in the basic wrap function regardless if the related policy is used or not. Let me take a closer look.

**Comment by min-xu-ai** [comment]
@QuentinDuval @SeanNaren 

#685 is my attempt to address this issue. Auto_wrap can still be called only once on a module (or sub-module) but users can get around that by pre-assign `wrapper_config` attributes to the modules. While this works, I feel it is not the most elegant since `default_auto_wrap_policy` has a default large param limit which may prevent traversal of some modules. This can be an easy-to-make mistake if they forget to change min_num_params to 0. If you have better ideas on how to address this, please let me know!
