### ISSUE TITLE
Controlling tiling/parallelism of individual  layers

### ISSUE THREAD

**Issue by mattiasmar** [facebookresearch/fairscale#655]
## ❓ Questions and Help
How does one control tiling/parallelism of individual layers?

**Comment by min-xu-ai** [comment]
@mattiasmar, thanks for the question. Can you elaborate a bit more? Is this related to DDP or SDP or FSDP or pipeline or in general? Do you have a small example to illustrate your needs?

**Comment by mattiasmar** [comment]
Well, I wanted to try non-symmetric split of the DNN. So some layers would be tiled in 10, others in more and yet others in less. I'd also like to add to that data parallelism for some of the layers. I think, but I'm not sure, that  I would need a combination of FSDP and pipeline.

**Comment by min-xu-ai** [comment]
Interesting. Can be explain a bit more what do you mean by “tiling”? Also, how do you imagine pipeline + FSDP? It seems to me that there is hardly a reason to combine them since either one should be enough for doing things in parallel.

**Comment by mattiasmar** [comment]
With tiling I mean splitting a layer by its weight. I believe this is what DeepSpeed intends with its method [TiledLinear](https://deepspeed.readthedocs.io/en/stable/zero3.html#deepspeed.zero.TiledLinear).
The intention is that multiple processors would split the computations of a layer among them. In my case I want to control per layer the number of splits used.

**Comment by min-xu-ai** [comment]
I see. That’s model parallel, like megatron from nvidia, right? FSDP also splits the weights among GPUs, but computation per layer is not split. I.e. full weights are gathered from all gpus before the compute. However, FSDP parallelize by data, I.e. data parallel. Is there a reason you can’t use data parallel fashion of training?

**Comment by mattiasmar** [comment]
That wasn't 100% clear to me.  If FSDP splits weights among GPU's, how are computations not split. I mean the computations follow the weights.

About FSDP's data parallelism: Can it be controlled on a per layer basis? If yes, how?

**Comment by min-xu-ai** [comment]
Good question. FSDP can be nested, I.e.

fsdp(fsdp (layer), ..., fsdp (layer))

user can control the nesting to make memory speed tradeoff. 

The weights are split but the compute is not. That’s because FSDP temporarily moves the weights back to each GPU to do the full compute. After that’s done, weights are split again to save memory. Via nesting, the peak memory is also reduced since only the max layer’s weights determines the peak, not sum of all layers.

**Comment by mattiasmar** [comment]
I assume the nested option ( fsdp(fsdp (layer), ..., fsdp (layer)) ) was a response to my question on data parallelism. Is there example code that demonstrates this that I could learn from that you would point me to?

About model parallelism: Now when we understand each other well, is there an option (perhaps non FSDP option) that would allow me to control per layer model parallelism (I would be interested in both directing complete layers to distinct GPU's and also in what I called 'tiling'; splitting a single layer over a specified number of cards)?

**Comment by min-xu-ai** [comment]
> I assume the nested option ( fsdp(fsdp (layer), ..., fsdp (layer)) ) was a response to my question on data parallelism. Is there example code that demonstrates this that I could learn from that you would point me to?

Definitely, check out `tests/nn/data_parallel/test_fsdp.*`. There are lot of examples.

> About model parallelism: Now when we understand each other well, is there an option (perhaps non FSDP option) that would allow me to control per layer model parallelism (I would be interested in both directing complete layers to distinct GPU's and also in what I called 'tiling'; splitting a single layer over a specified number of cards)?

I unfortunately have not investigated model parallel techniques in detail. A recent work called torchshard, which might be helpful to you: https://github.com/KaiyuYue/torchshard

**Comment by min-xu-ai** [comment]
BTW, feel free to close this issue if there are no additional questions. :-)

**Comment by mattiasmar** [comment]
Thanks for all your responses.
