### ISSUE TITLE
[cleanup] Move to using torch.distributed.broadcast_object_list instead of fairscale.optim.utils.broadcast_object

### ISSUE THREAD

**Issue by anj-s** [facebookresearch/fairscale#663]
## Cleanup/Refactor
This is a cleanup that we should perform in order to use the latest PyTorch APIs. Currently we support PyTorch 1.6, 1.7 and 1.8. Previous version did not have support for broadcast_object_list which is why we used the FairScale utility [function](https://github.com/facebookresearch/fairscale/commit/2d9542030b245abef323d61e02a8d67e92977918)

**Comment by anj-s** [comment]
1.7 does not have support for torch.distributed.broadcast_object_list which means this might need an if/else for the time being until we support the next PyTorch version.

**Comment by min-xu-ai** [comment]
This has been done in #744. It turns out to be not easy to debug the hang of the new function on older GPUs. All good now. :-)
