### ISSUE TITLE
FSDP(checkpoint()) causing issues in the optimizer when returning to training after evaluating

### ISSUE THREAD

**Issue by epwalsh** [facebookresearch/fairscale#710]
## 🐛 Bug

When wrapping a `module` with `FSDP(checkpoint_wrapper(module))`, the first training epoch and validation pass go fine, but the second training pass will fail due to a size mismatch of gradients.

## To Reproduce

I modified a test in https://github.com/facebookresearch/fairscale/pull/709/files to show the failure. This PR also includes a work-around. But I'm still not entirely sure what causes the bug.

**Comment by epwalsh** [comment]
I'll look into this more tomorrow, just wanted to open this up now in case anyone else has an idea about what's going on.

**Comment by min-xu-ai** [comment]
Thanks for reporting and working on a fix! I am not sure the issue is within checkpoint_wrapper or it is within fsdp?

I don't quite understand the test you have in the PR. It seems being doing training with grad accumulation not validation. Am I missing something?

**Comment by epwalsh** [comment]
Sorry the test isn't very clear, I'll put together a simpler example tomorrow. But the main point is that this test will fail on the next training batch following a single eval batch.
