### ISSUE TITLE
[FSDP] `is_flattened` property changes to False when we enter summon_params context.

### ISSUE THREAD

**Issue by anj-s** [facebookresearch/fairscale#745]
## 🐛 Bug

We lose the `is_flattened` property of the FlattenParamsWrapper object the moment we call [enter_context](https://github.com/facebookresearch/fairscale/blob/8bca4f87ac070f6e5ae2fc74c9635b2aaa9a2208/fairscale/nn/data_parallel/fully_sharded_data_parallel.py#L815). This should not happen since is_flattened should only change when we are in a unflatten_params context.  This happens with recurse=True or recurse=False. 

To reproduce, add a print statement before line 815 in the above linked code snippet and a print statement perhaps in the context of a with summon_full_params() function. You should be able to see that the two values are different. For example:
```
print(f"outside stack: self._fsdp_wrapped_module.is_flattened {self._fsdp_wrapped_module.is_flattened}")
with self.summon_full_params(recurse=False):
            print(f"inside stack: self._fsdp_wrapped_module.is_flattened {self._fsdp_wrapped_module.is_flattened}")
            // code in the context that requires all params on one device.

**Comment by min-xu-ai** [comment]
Maybe I am missing something but summon_full_params does enter unflatten_params context before yielding. In my current branch `min/fsdp`, it looks like:

![image](https://user-images.githubusercontent.com/24926999/126851631-0b18fe6f-10d4-4698-9f50-ad158a627f3e.png)


This is needed since we want the summon context to expose the views of unflatten params (separate, original parameters, not concat, flat parameters).

Maybe this is an expected behavior?

**Comment by anj-s** [comment]
May it is expected behavior to enter the context of unflatten_params but it does not seem right if you have a FlattenParamsWrapper which no longer has an is_flattened=True property that was previously set.  

Here are some places that I think it could be an issue:
* If I want to perform an operation in the context of summon_params differently for flattened and unflattened params it is hard to find the right boolean to switch on.
* The type that _fsdp_wrapped_module contains is different for flattened and unflattened params and this does not change in any context.
* We have tightly coupled summon_full_params with unflatten but could there be use cases where we summon full params but don't want any views? maybe for checkpointing?

I now wait till I am out of the summon_params context to figure out how to handle flattened vs unflattened params. This is not a P0 because there are workarounds and if conditions that can be added but seems like something we will trip over again. 

Closing this bug because I am looking into this as part of [named_parameter](https://github.com/facebookresearch/fairscale/issues/569) support. Will update findings and approach there.

**Comment by min-xu-ai** [comment]
Thanks for sharing your thoughts. Flatten and all the param name mangling is tricky. I hope we can simplify it. Please take a look at my outstanding PR to see if it affect your "named_parameter" change or not. To me FSDP is complex and anyway we can simplify and/or modularity it, it would be really good.
