### ISSUE TITLE
What is pointwise optimizer and non-pointwise optimizer?  

### ISSUE THREAD

**Issue by vycezhong** [facebookresearch/fairscale#767]
## ❓ Questions and Help

Hey. I am reading the documentation of FSDP and I am confused with the following sentences. 

> 4. Results should be identical to DDP with pointwise Optimizers, e.g., Adam, AdamW, Adadelta, Adamax, SGD, etc.. However, the sharding will result in slightly different results when using non-pointwise Optimizers, e.g., Adagrad, Adafactor, LAMB, etc.

I don't quite understand the meaning of "pointwise optimizer". Why Adagrad, Adafactor, LAMB, etc are not pointwise optimizers? Thanks!

**Comment by min-xu-ai** [comment]
Hi, thanks for the question and sorry the delayed reply.

By "point wise", it means the delta value computed for each parameter only based on that "point", i.e. the gradient value for that weight only. The delta can't be computed based on things like the tensor's norm or some global value that might not be available when the parameter and gradient are sharded (i.e. distributed across all ranks).

Hope this answers your questions.
