### ISSUE TITLE
Does Pipe supports multi-machine training

### ISSUE THREAD

**Issue by vycezhong** [facebookresearch/fairscale#768]
I have two machines, each equipped with 4 GPUs. I wonder if I can achieve a pipeline cross 8 GPUs like this. 

[GPU0 -> GPU1 -> GPU2 -> GPU3] -> [GPU0 -> GPU1 -> GPU2 -> GPU3]

**Comment by anj-s** [comment]
@vycezhong Currently nn.Pipe supports a single machine single process implementation so the above configuration is not possible. Once we implement multiprocess pipe that also spans multiple machines we should be able to implement 1 pipeline across 8 GPUs.
