### ISSUE TITLE
i use fairscale oos , sharddp and FSDP on one single mutil-gpu,

### ISSUE THREAD

**Issue by daixiangzi** [facebookresearch/fairscale#770]
## ❓ Questions and Help
use oss gpu-memory reduce just a few on res101,but use sharddp and FSDP increase gpu-memory

**Comment by anj-s** [comment]
@daixiangzi that is definitely not expected behavior. can you elaborate on your use case and provide a small repro?

**Comment by min-xu-ai** [comment]
No update for 7 days. Close for now. Reopen if there is new updates.
