### ISSUE TITLE
Incorrect usage of FSDP & misc questions

### ISSUE THREAD

**Issue by aluo-x** [facebookresearch/fairscale#776]
I'm currently trying to use FSDP and the behavior is very different from what I expect, whereas ShardedDDP behaves as I expect. I have seen #423 and have modified my torch DDP code with an additional `torch.cuda.set_device(device)`.

Minimal example:
```
import torch
import torch.distributed as dist
import torch.nn as nn
import torch.optim as optim
import torch.multiprocessing as mp

from torch.nn.parallel import DistributedDataParallel as DDP
from fairscale.nn.data_parallel import ShardedDataParallel as ShardedDDP
from fairscale.optim.oss import OSS
from fairscale.nn.data_parallel import FullyShardedDataParallel as FSDP
import os

class Generator(nn.Module):
    def __init__(self):
        super(Generator, self).__init__()
        self.net1 = nn.Linear(10,10)
        self.net1.weight.data = torch.zeros_like(self.net1.weight.data)

    def forward(self, x):
        return self.net1(x)

def setup(rank, world_size):
    os.environ['MASTER_ADDR'] = 'localhost'
    os.environ['MASTER_PORT'] = '12355'

    # initialize the process group
    dist.init_process_group("nccl", rank=rank, world_size=world_size)

def cleanup():
    dist.destroy_process_group()

def demo_basic(rank, world_size):
    setup(rank, world_size)
    torch.cuda.set_device(rank)
    G = Generator().to(rank)
    optimizer_G = OSS(params=G.parameters(), optim=torch.optim.SGD, **{ "lr": 1e-3})
    # ddp_model_G = DDP(G, device_ids=[rank])
    # ddp_model_G = ShardedDDP(G, [optimizer_G])
    ddp_model_G = FSDP(G)

    for k in range(10):
        # optimizer_G.zero_grad(set_to_none=True)
        ddp_model_G.zero_grad()
        loss = torch.sum(ddp_model_G(torch.randn(20, 10).to(rank)))
        loss.backward()
        optimizer_G.step()
        # loss.backward()
        if rank==0:
            print(loss)

```

If I manually zero out the weights, there are no gradients, and the loss does not change. The same code works under DDP & ShardedDDP. 

Additionally I was curious about two things:
1. What is the correct way to log the loss? Do we simply track the rank 0 loss?
2. What is the correct way to save the state_dict under FSDP? Under DDP, the weight from rank 0 is saved. A small code sample would be appreciated. 
3. Similarly, what is the canonical way to restore weights?

**Comment by aluo-x** [comment]
After closely looking at the code under tests, I notice that for FSDP - the optimizer is [created after converting a model](https://github.com/facebookresearch/fairscale/blob/73f73120fed1bc806d7487dcc4e999ad63e12947/tests/nn/data_parallel/test_fsdp_freezing_weights.py#L74) using FSDP. 

But for the example given in the [OSS tutorial](https://fairscale.readthedocs.io/en/latest/tutorials/oss.html) the optimizer is created prior to conversion using DDP or ShardedDPP (code example for FSDP is incomplete). For reference, the pytorch tutorial also creates [their optimizer after converting](https://pytorch.org/tutorials/intermediate/ddp_tutorial.html) using DDP.

I feel like the tutorial could be updated with a small note for this issue, and the documentation regarding #423 could also be more explicit. 

Still would appreciate any tips on the correct way to do state_dict saving and loading using FSDP.

**Comment by aluo-x** [comment]
Currently my FSDP state_dict does not appear to be identical numerically to DDP/ShardedDDP. I use fixed network initializations and fixed inputs. DDP is identical to SDDP, but they are not identical to FSDP
Minimum repro:
```
import torch
import torch.distributed as dist
import torch.nn as nn
import torch.multiprocessing as mp

from torch.nn.parallel import DistributedDataParallel as DDP
from fairscale.nn.data_parallel import ShardedDataParallel as ShardedDDP
from fairscale.optim.oss import OSS
from fairscale.nn.data_parallel import FullyShardedDataParallel as FSDP
import os

class Generator(nn.Module):
    def __init__(self):
        super(Generator, self).__init__()
        self.net1 = []
        for k in range(4):
            self.net1.append(nn.Linear(10,10))
            self.net1[-1].weight.data = torch.ones_like(self.net1[-1].weight.data)
            self.net1[-1].bias.data = torch.ones_like(self.net1[-1].bias.data)
            self.net1.append(nn.LeakyReLU(negative_slope=0.1))
        self.net1 = nn.Sequential(*self.net1)


    def forward(self, x):
        return self.net1(x)

class Discrim(nn.Module):
    def __init__(self):
        super(Discrim, self).__init__()
        self.net1 = []
        for k in range(4):
            self.net1.append(nn.Linear(10, 10))
            self.net1[-1].weight.data = torch.ones_like(self.net1[-1].weight.data)
            self.net1[-1].bias.data = torch.ones_like(self.net1[-1].bias.data)
            self.net1.append(nn.LeakyReLU(negative_slope=0.1))
        self.net1.append(nn.Linear(10, 1))
        self.net1[-1].weight.data = torch.ones_like(self.net1[-1].weight.data)
        self.net1[-1].bias.data = torch.ones_like(self.net1[-1].bias.data)
        self.net1 = nn.Sequential(*self.net1)

    def forward(self, x):
        return self.net1(x)


def setup(rank, world_size):
    os.environ['MASTER_ADDR'] = 'localhost'
    os.environ['MASTER_PORT'] = '12353'

    # initialize the process group
    dist.init_process_group("nccl", rank=rank, world_size=world_size)

def cleanup():
    dist.destroy_process_group()

def demo_basic(rank, world_size):
    # mode = "ddp"
    # mode = "sddp"
    mode = "fsdp"

    print(f"Running basic DDP example on rank {rank}.")
    setup(rank, world_size)
    torch.cuda.set_device(rank)

    G = Generator()
    if os.path.exists("state_G.ckpt"):
        dist.barrier()
        G.load_state_dict(torch.load("state_G.ckpt"))
    G.to(rank)

    D = Discrim()
    if os.path.exists("state_D.ckpt"):
        dist.barrier()
        D.load_state_dict(torch.load("state_D.ckpt"))
    D.to(rank)


    if mode == "ddp":
        # Optimizer after DDP (follow pytorch tutorial)
        ddp_model_G = DDP(G, device_ids=[rank])
        optimizer_G = OSS(params=G.parameters(), optim=torch.optim.SGD, **{"lr": 1e-4})

        ddp_model_D = DDP(D, device_ids=[rank])
        optimizer_D = OSS(params=D.parameters(), optim=torch.optim.SGD, **{"lr": 1e-4})

    elif mode == "sddp":
        # Optimizer before SDDP
        optimizer_G = OSS(params=G.parameters(), optim=torch.optim.SGD, **{"lr": 1e-4})
        ddp_model_G = ShardedDDP(G, [optimizer_G])

        optimizer_D = OSS(params=D.parameters(), optim=torch.optim.SGD, **{"lr": 1e-4})
        ddp_model_D = ShardedDDP(D, [optimizer_D])

    elif mode == "fsdp":
        # Optimizer after FSDP
        ddp_model_G = FSDP(G)
        optimizer_G = OSS(params=ddp_model_G.parameters(), optim=torch.optim.SGD, **{"lr": 1e-4})

        ddp_model_D = FSDP(D)
        optimizer_D = OSS(params=ddp_model_D.parameters(), optim=torch.optim.SGD, **{"lr": 1e-4})



    for iter_idx in range(10):
        ddp_model_G.zero_grad(set_to_none=False)
        loss_G = torch.sum(ddp_model_G(torch.ones(20, 10).to(rank)))
        loss_G.backward()
        optimizer_G.step()

        ddp_model_D.zero_grad(set_to_none=False)
        loss_D = torch.sum(ddp_model_D(torch.ones(5, 10).to(rank)))
        loss_D.backward()
        optimizer_D.step()


        if mode == "ddp":
            if rank==0 and iter_idx==9:
                state = ddp_model_G.module.state_dict()
                for k in state:
                    state[k] = state[k].cpu()
                # print(state)
        elif mode == "sddp":
            if rank==0 and iter_idx==9:
                state = ddp_model_G.module.state_dict()
                for k in state:
                    state[k] = state[k].cpu()
                # print(state)
        elif mode == "fsdp":
            if iter_idx == 9:
                state = ddp_model_G.state_dict()
                if rank==0:
                    for k in state:
                        state[k] = state[k].cpu()
                    # print(state)
        if iter_idx == 9 and rank == 0:
            print("Counting unique values, should be size one in each matrix")
            for k in state:
                print(torch.unique(state[k]))
            # torch.save(state, "state.ckpt")
    cleanup()


def run_demo(demo_fn, world_size):
    mp.spawn(demo_fn,
             args=(world_size,),
             nprocs=world_size,
             join=True)

if __name__ == "__main__":
    n_gpus = torch.cuda.device_count()
    assert n_gpus >= 2, f"Requires at least 2 GPUs to run, but got {n_gpus}"
    world_size = n_gpus
    print(world_size)
    run_demo(demo_basic, world_size)
```

DDP/SDDP output:
```
Counting unique values, should be size one in each matrix
tensor([-0.7564])
tensor([-0.7564])
tensor([-0.9835])
tensor([0.5784])
tensor([-0.9926])
tensor([1.0000])
tensor([-0.9969])
tensor([0.9800])
```
FSDP output:
```
Counting unique values, should be size one in each matrix
tensor([-0.8305, -0.8271])
tensor([-0.8305, -0.8271])
tensor([-1.0239, -1.0236, -0.8271])
tensor([-0.8305, -0.8271])
tensor([-1.0239, -1.0236, -0.8305, -0.8271])
tensor([-0.8271])
tensor([-1.0239, -1.0236, -0.8305, -0.8271])
tensor([-1.0239, -1.0236])
```
Run on 3 GPUs:
`CUDA_VISIBLE_DEVICES=1,2,3 python new_trainer.py`
DDP/SDDP/FSDP controlled via the mode variable in the `demo_basic` function.

**Comment by min-xu-ai** [comment]
Thank you for the issue report, @aluo-x!

This part of the code:

![image](https://user-images.githubusercontent.com/24926999/132146770-d7d787a6-5495-4929-aedb-4bf97454168a.png)


FSDP does not need OSS. FSDP itself already take care of optimizer state being sharded so OSS is not needed to shard the state again. We have not tested FSDP + OSS as you are using it here and that's probably why you are seeing problem. Can you try FSDP without OSS?

In terms of state_dict:

- if your model is small, you can do state_dict on rank 0, like DDP and save the value that way. But be aware that if you have flatten_parameter=True (the default for FSDP), then the state_dict isn't the same the DDP during parameter flattening. This behavior may change in the future to match DDP.
- if your model is big, you want to use local_state_dict() to save on all ranks and restore them on all ranks. The fairseq and vissl libraries may have good examples around how to deal with state checkpointing (including the optimizer state in the checkpoint). The usability and documentation in this area is not very good currently. CCing @zhaojuanmao for her info.

**Comment by aluo-x** [comment]
@min-xu-ai I can confirm that after removing OSS, the results for FSDP numerically match those of DDP and SDDP. I was initially confused because FSDP was [included under the OSS tutorial](https://fairscale.readthedocs.io/en/latest/tutorials/oss.html) with an incomplete code.

Can you clarify or provide a code snippet for model saving/loading under FSDP? I tried running `.state_dict()` under rank 0 only but encountered an error
```
  File "/home/aluo/anaconda3/envs/torch190/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 59, in _wrap
    fn(i, *args)
  File "/home/aluo/PycharmProjects/InfiniteScene/new_trainer.py", line 131, in demo_basic
    state = ddp_model_G.module.state_dict()
  File "/home/aluo/anaconda3/envs/torch190/lib/python3.8/site-packages/fairscale/nn/misc/flatten_params_wrapper.py", line 403, in state_dict
    with self.unflatten_params():
  File "/home/aluo/anaconda3/envs/torch190/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/home/aluo/anaconda3/envs/torch190/lib/python3.8/site-packages/fairscale/nn/misc/flatten_params_wrapper.py", line 367, in unflatten_params
    self._unflatten_params(cast(Optional[List[Optional[Tensor]]], flat_params))
  File "/home/aluo/anaconda3/envs/torch190/lib/python3.8/site-packages/fairscale/nn/misc/flatten_params_wrapper.py", line 318, in _unflatten_params
    ps = self.get_param_views(external_data)
  File "/home/aluo/anaconda3/envs/torch190/lib/python3.8/site-packages/fairscale/nn/misc/flatten_params_wrapper.py", line 460, in get_param_views
    gens.append(p.get_param_views(data))
  File "/home/aluo/anaconda3/envs/torch190/lib/python3.8/site-packages/fairscale/nn/misc/flatten_params_wrapper.py", line 88, in get_param_views
    raise ValueError(
ValueError: Incorrect numel of supplied data: got 147 but expected 440
```
Additionally the [API documentation for FSDP](https://fairscale.readthedocs.io/en/latest/api/nn/fsdp.html) states that `This needs to be called on all ranks, since synchronization primitives will be used.`

An example for optimizer saving/loading under FSDP would also be appreciated.

**Comment by min-xu-ai** [comment]
Thanks Andrew for reporting the doc issues! CC other team members on that: @anj-s @tmarkstrum @blefaudeux 

I misspoke before, yes, you need to call state_dict on all ranks, but only rank 0 should save it. When you load it back, all ranks should load from the same file rank 0 saved.

I wish I have a more comprehensive example code, but I don't know if we have any. We will look into adding one for sure! cc: @zhaojuanmao for her info.

**Comment by blefaudeux** [comment]
> Thanks Andrew for reporting the doc issues! CC other team members on that: @anj-s @tmarkstrum @blefaudeux

It's something I just referenced in another issue, I agree that [this part of the doc](https://fairscale.readthedocs.io/en/latest/tutorials/oss.html) may be confusing in hindsight, it's basically three tutorials back to back and it's not obvious to extract the structure from it ? It used to be only for OSS as evidenced by the URL, I think that it could be easier to keep the 3 (OSS, OSS+Sharded, FSDP) separate. Note that this is all hindsight, I did not realize this when we changed it

**Comment by aluo-x** [comment]
Thanks to @blefaudeux and @min-xu-ai for the helpful comments. 

I took a look at Fairseq and vissl code bases, and found the code for sharded saving. But there was still quite a bit of boiler plate that seemed unecessary outside of fairseq/vissl.

For future reference [here is a simple snippet](https://gist.github.com/aluo-x/85fda4f4f10895963d94000cf084514e) demonstrating consolidated state_dicts and consolidated optimizer_states for FSDP and OSS (without FSDP). I'm not quite sure the `dist.barrier()` calls are needed. It is not quite complete, in particular I only do OSS loading/saving under ShardedDDP, but it can be easily extended to DDP. 

I felt like there are a few aspects of Fairscale's documentation that could be improved:

- full examples for OSS/FSDP that are complete, and demonstrate state_dict saving & loading, as well as `mp.spawn` setup
  - In particular for ShardedDDP, optimizer must be setup prior to converting the model to ShardedDDP. For FSDP, the optimizer must be setup after converting the model to FSDP
  - For FSDP at least (not sure for ShardedDDP), `torch.cuda.set_device(device)` must be set. This is unlike the default Pytorch DDP
  - OSS cannot be used with FSDP
- For FSDP state_dicts, the `.state_dict()` call must be made on all devices. While saving is done on one device like Pytorch DDP
- For OSS state_dicts, the `consolidate_state_dict` call should be made on all devices prior to calling `state_dict`
- DDP & ShardedDDP create state_dicts where parameter names contain `.module` unless you explicitly call `net.module.state_dict()`. For FSDP, the state_dicts do not contain `.module` in the parameter names

> But be aware that if you have flatten_parameter=True (the default for FSDP), then the state_dict isn't the same the DDP during parameter flattening. This behavior may change in the future to match DDP.

I'm not quite clear about what this means.

**Comment by min-xu-ai** [comment]
Feel free to send us PRs to change thing to the better if you want!

**Comment by blefaudeux** [comment]
Thanks @aluo-x for this feedback, as @min-xu-ai mentioned above feel free to submit PRs, else we'll try to improve this over time but we do have blind spots. The above is definitely helpful

**Comment by anj-s** [comment]
@aluo-x  Thank you for the detailed feedback about our docs! We'll definitely incorporate and improve our documentation. cc @tmarkstrum who is organizing our docs fixit soon.

**Comment by min-xu-ai** [comment]
Feel free to reopen or create new issues. PRs are always welcomed too! Thanks!
