### ISSUE TITLE
Errors with multiple passes through checkpointed module with FSDP

### ISSUE THREAD

**Issue by dbarnhart** [facebookresearch/fairscale#777]
FSDP fails when there are multiple passes through a checkpointed module wrapped as `checkpoint(FSDP(module))` with resharding after forward and no forward counters. There may also be a race condition between gradient accumulation and gradient reduction/resharding.

I have been able to fix the breakage, and propose a fix to the potential race condition, described in more detail below.

When we have a checkpointed FSDP module called multiple times as described above, I believe the control flow we would like is as follows:
1. Start checkpointed forward
2. Collect full params
3. _Skip_ register post backward hooks, since no-grad
4. Checkpoint inputs
5. Run forward with no-grad
6. Free full params
7. _Skip_ register pre backward hooks, since no-grad

...Time passes...

8. Repeat from step 1 some number of times.

...Time passes...

9. Start checkpointed backwards
10. Clear pre backward hook flag, `_pre_backward_hook_has_run = False`.
    * This is required for gradients to be prepared correctly when there are multiple checkpointed forward passes. Otherwise, it will be left as `True` and gradient accumulation will break. The the current _sharded_ grads are retained on `.grad` instead of cached, then autograd tries to accumulate into them using the _unsharded_ gradients, which has a shape mismatch.
11. Collect full params
12. Register post backward hooks
13. Run forward with grad
14. Register pre backward hooks
15. _Skip_ free full params
    * We are about to call `autograd.backward`, so resharding is a waste.
16. Call `autograd.backward`
17. First pre backward hook is called, and sets the guard flag `_pre_backward_hook_has_run`
18. _Block_ until all async `_post_reduction_hook` work completes for this module's parameters.
19. Call `_prep_grads_for_backward`
    * When resharding, this method caches the current (sharded) gradient for correct accumulation. This matters any time backprop visits a parameter multiple times, when resharding happens between visits. Hence we block on step 18, to ensure the reduction/resharding is complete before caching the current gradient for later accumulation. In practice, I have not seen this race condition come up, as it may be prevented by other synchronization. But I would be more comfortable if there was a strong guarantee here.
20. Backwards computation runs
21. For each parameter, call `_post_backward_hook` after its gradient is computed
22. _Remove_ the `_post_backward_hook` via the handle in `param._shard_bwd_hook`.
    * This isn't apparently necessary, and works fine if you retain the hook. That is, the hook appears to remain valid across multiple parameter reshardings. But dropping it here restores the parameters to their initial state, which seems more hygienic.
    * That said, it does seem to be possible for this hook to become invalidated, under the right conditions. Wrapping as FSDP(checkpoint(wrapper)) still fails with the post backward hook not being called for repeated recomputations of a checkpointed module. It seems wise to drop the hook as soon as possible. Though that doesn't fix this particular failure, for unknown reasons.
23. Free the full parameters
24. Start the async gradient sync/reshard task for this parameter. Track the set of pending jobs somehow.

...A small amount of time passes...

25. _post_reduction_hook runs, and sharded gradients accumulate

...Time passes...

26. Repeat from step 8 some number of times

...Time passes...

27. Backwards pass complete

In summary:
* The most important fix is resetting the guard in step 10.
* I haven't actually observed the race condition considered in step 19, even with explicit checks. It's possible I'm misunderstanding something.
* Disabling resharding during checkpoint recomputation is purely an optimization. Things appear to work with and without it.
* These are tricky issues, so I would very much appreciate extra eyes.

Notes:
* This PR (https://github.com/facebookresearch/fairscale/pull/476) appears to look at some of these issues but never merged. Having the checkpoint wrapper detect if its wrapping an FSDP instance, and disabling resharding during recomputation, addresses the concerns raised in that PR by @myleott.
* There are still other issues when wrapping as FSDP(checkpoint(module)). In particular, the post backward hook only fires for the last of any repeated forwards, instead of all of them. I gave up on it, pending a more reliable post-backward hooking mechanism, as the approach outlined here seems efficient. While I suspect cases like FSDP(Sequence(moduleA, checkpointed(moduleB), moduleC)) will still break, my use case has no nested checkpointing like this.

**Comment by min-xu-ai** [comment]
Thanks for the detail issue report @dbarnhart.

The proposed fix for checkpoint(FSDP(module)) seems reasonable but I remember we preferred FSDP(checkpoint(module)) so that all-gather is not done one extra time. i.e.:

* checkpoint(FSDP(module))
  - fwd during fwd - all gather
  - fwd during bwd - all gather
  - bwd during bwd - all gather
* FSDP(checkpoint(module))
  - fwd during fwd - all gather
  - fwd during bwd - all gather
  - bwd during bwd - NO all gather

Let's call those two methods `method CF` and `method FC`.

If I am not mistaken, I think you are suggesting that we can make FSDP more aware that it is in a checkpoint wrapper and then optimize away the extra all gather. I have not attempted it, partially because I do not want to make FSDP overly complicated and too deeply coupled with checkpoint. But if you have a clean PR on that please definitely share it.

Is my understanding correct that you prefer `method CF` because `method FC` is missing some callback that you want to hook into? Can you provide more details of what do you want to achieve in the end?

As you know, checkpoint and double fwd pass is a tough case. We have a unit test that does cover the method FC case to some extend. I just merged a fix that fixed a bug uncovered by the pytorch 1.10 nightly build in that case. Feel free to take a look at the commit and let me know what's missing in method FC?

**Comment by dbarnhart** [comment]
The unit tests in [test_fsdp_multiple_forward_checkpoint.py](https://github.com/facebookresearch/fairscale/blob/4f7f0853cd2d5bfaefeba5931be983e02a35fcd8/tests/nn/data_parallel/test_fsdp_multiple_forward_checkpoint.py) deal with the case where `reshard_after_forward=False` and `flatten_parameters=False`. I'm interested in the case where `reshard_after_forward=True` and `flatten_parameters=True`, which breaks for me with either method.

The only way I've been able to make that work is by using `method CF` with the changes described above. Principally, setting `_pre_backward_hook_has_run = False` at the start of the FSDP forward method.

I saw the fix for pytorch 1.10, but that appears unrelated. It has no effect on my testing.

**Comment by min-xu-ai** [comment]
The unit test should test both flatten and nonflatten via this line:

```
 @pytest.mark.parametrize("flatten", ["flatten", "no_flatten"])
```

`reshard_after_forward` should default to True.

There is a fsdp_config that is used when sync_bn is tested and flatten and reshard are False in that case.

Just to test it out, using pytorch version `1.10.0.dev20210901+cu111`, I enabled those 2 flags. The unit test seems to run fine on my system. Can you paste your error on your system?

my local change while doing the test:

```
--- a/tests/nn/data_parallel/test_fsdp_multiple_forward_checkpoint.py
+++ b/tests/nn/data_parallel/test_fsdp_multiple_forward_checkpoint.py
@@ -78,8 +78,8 @@ def _create_model(
         model = nn.SyncBatchNorm.convert_sync_batchnorm(model)
         fsdp_config = {
             "mixed_precision": False,
-            "flatten_parameters": False,
-            "reshard_after_forward": False,
+            "flatten_parameters": True,
+            "reshard_after_forward": True,
             "bucket_cap_mb": 0,
             "force_input_to_fp32": True,  # SyncBN needs this.
         }
```

**Comment by dbarnhart** [comment]
I took a quick look.

The test fails when you omit the override `compute_dtype=torch.float32`. In mixed precision mode, it seems that when the_fp16_shard is actually fp16, the post-backward hooks don't fire, and we get an error in `method FC`. I don't know why.

In particular, I ran:
`python -m pytest -s tests/nn/data_parallel/test_fsdp_multiple_forward_checkpoint.py::test_multiple_forward_checkpoint[bn-model2-no_auto_wrap_bn-flatten-mixed]`

The error:
```
Loss 0 : 2.25244140625
Loss 0 : 2.25244140625
Asserting FSDP instance is: FullyShardedDataParallel(
  world_size=2, flatten_parameters=True, mixed_precision=True, 
  (_fsdp_wrapped_module): FlattenParamsWrapper(
    (_fpw_module): Sequential(
      (0): Conv2d(4, 4, kernel_size=(3, 3), stride=(1, 1))
      (1): BatchNorm2d(4, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (2): ReLU()
    )
  )
)
ERROR: expected to be in states [<TrainingState.BACKWARD_POST: 4>] but current state is TrainingState.BACKWARD_PRE
  File "/home/darryl/miniconda3/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "/home/darryl/Projects/fairscale/fairscale/nn/data_parallel/fully_sharded_data_parallel.py", line 1474, in _wait_for_post_backward
    m.assert_state(TrainingState.BACKWARD_POST)
  File "/home/darryl/Projects/fairscale/fairscale/nn/data_parallel/fully_sharded_data_parallel.py", line 1833, in assert_state
    traceback.print_stack()
FAILED
```

**Comment by min-xu-ai** [comment]
Thank you! This makes a lot of sense. I suspect the same will fail on my system but I haven't tried it.

I recall we had issues like this in the past when AMP is involved and some hooks are affected since AMP replaces tensors with different dtypes underneath the model and FSDP code. See this comment:

https://github.com/facebookresearch/fairscale/blob/4f7f0853cd2d5bfaefeba5931be983e02a35fcd8/fairscale/nn/data_parallel/fully_sharded_data_parallel.py#L1253

I don't fully understand the internals of pytorch for the `grad_acc` and AMP and hook interactions. But if in your model code you can remove AMP and keep everything fp16 or cast them by hand, perhaps this issue will go away? Otherwise, you will have to play with the grad_acc registration order for the multiple fwd pass code to see what's the best way for your training.

I'd be curious to know what you will try and find out.

**Comment by dbarnhart** [comment]
I suppose then its interesting that `method CF` actually does work with AMP. We'll stick with that method for now.

**Comment by min-xu-ai** [comment]
> I suppose then its interesting that `method CF` actually does work with AMP. We'll stick with that method for now.

Just to avoid confusion, I think there is MP vs. AMP, i.e. without `autocast` and without `autocast` contexts. In my incomplete and limited experiences, the `autocast` context can potentially cause this issue you are seeing in some cases.

**Comment by min-xu-ai** [comment]
Feel free to reopen or create a new issue if there are specific things we can do. PRs are always welcomed too!

**Comment by dbarnhart** [comment]
Reopening, as there seems to be a more fundamental issue here unrelated to any kind of mixed precision, and the race condition I mentioned appears real.

It seems that when `method FC` is used, setting `maintain_forward_counter=False` in `checkpoint_wrapper` is **not optional**, as I would expect.

The forward counters seem like a trade-off. With them, you can reduce network overhead at the cost of more VRAM, by delaying the free of the full parameters. But in my use case, I have a multiple large modules that would be subject to this delayed free, so it's untenable. So it doesn't seem like counters should be required.

The unit test fails to capture this error, because the weight tensors are so small that the race condition I was concerned about actually happens. If you make the weights a little larger or force synchronous gradient reduction, the test will fail. See the diffs below for how to trigger it.

Diff for unit test
```
diff --git a/tests/nn/data_parallel/test_fsdp_multiple_forward_checkpoint.py b/tests/nn/data_parallel/test_fsdp_multiple_forward_checkpoint.py
index b4127bc..6776e79 100644
--- a/tests/nn/data_parallel/test_fsdp_multiple_forward_checkpoint.py
+++ b/tests/nn/data_parallel/test_fsdp_multiple_forward_checkpoint.py
@@ -56,10 +56,10 @@ class Model2(nn.Module):
 
     def __init__(self):
         super().__init__()
-        self.block1 = nn.Sequential(nn.Conv2d(3, 4, kernel_size=3), nn.BatchNorm2d(4), nn.ReLU(inplace=True))
-        self.block2 = nn.Sequential(nn.Conv2d(4, 4, kernel_size=3), nn.BatchNorm2d(4), nn.ReLU(inplace=False))
-        self.block3 = nn.Sequential(nn.Conv2d(4, 8, kernel_size=3), nn.BatchNorm2d(8), nn.ReLU(inplace=True))
-        self.head = nn.Sequential(nn.AdaptiveAvgPool2d(output_size=(1, 1)), nn.Flatten(), nn.Linear(8, 10))
+        self.block1 = nn.Sequential(nn.Conv2d(3, 400, kernel_size=3), nn.BatchNorm2d(400), nn.ReLU(inplace=True))
+        self.block2 = nn.Sequential(nn.Conv2d(400, 400, kernel_size=3), nn.BatchNorm2d(400), nn.ReLU(inplace=False))
+        self.block3 = nn.Sequential(nn.Conv2d(400, 800, kernel_size=3), nn.BatchNorm2d(800), nn.ReLU(inplace=True))
+        self.head = nn.Sequential(nn.AdaptiveAvgPool2d(output_size=(1, 1)), nn.Flatten(), nn.Linear(800, 10))
 
     def forward(self, x):
         if isinstance(x, torch.Tensor):
@@ -91,9 +91,9 @@ def _create_model(
             if with_model2:
                 model.block3 = auto_wrap_bn(model.block3, single_rank_pg=False, fsdp_config=fsdp_config)
         if with_checkpoint:
-            model.block2 = checkpoint_wrapper(model.block2, maintain_forward_counter=True)
+            model.block2 = checkpoint_wrapper(model.block2, maintain_forward_counter=False)
             if with_model2:
-                model.block3 = checkpoint_wrapper(model.block3, maintain_forward_counter=True)
+                model.block3 = checkpoint_wrapper(model.block3, maintain_forward_counter=False)
         with enable_wrap(
             wrapper_cls=FSDP,
             flatten_parameters=flatten,
```

Alternatively, force synchronous reduction, and the unit test will fail with small weights.
```
diff --git a/fairscale/nn/data_parallel/fully_sharded_data_parallel.py b/fairscale/nn/data_parallel/fully_sharded_data_parallel.py
index f9a75c8..b77bc08 100644
--- a/fairscale/nn/data_parallel/fully_sharded_data_parallel.py
+++ b/fairscale/nn/data_parallel/fully_sharded_data_parallel.py
@@ -1360,6 +1360,8 @@ class FullyShardedDataParallel(nn.Module):
                 assert self._reducer is not None
                 grad_chunks = chunk_and_pad(param.grad.data, self.world_size)
                 self._reducer.reduce_scatter_async(grad_chunks, group=self.process_group, callback_fn=callback_fn)
+                self._reducer.flush()
+                self._streams["post_backward"].synchronize()
             else:
                 # Currently the only way for _is_sharded to be False is if
                 # world_size == 1. This could be relaxed in the future, in which
```

Example error:

`NCCL_P2P_DISABLE=1 python -m pytest -s tests/nn/data_parallel/test_fsdp_multiple_forward_checkpoint.py::test_multiple_forward_checkpoint[bn-model2-no_auto_wrap_bn-flatten-full]`
```
E       torch.multiprocessing.spawn.ProcessRaisedException: 
E       
E       -- Process 1 terminated with the following error:
E       Traceback (most recent call last):
E         File "/home/darryl/miniconda3/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 59, in _wrap
E           fn(i, *args)
E         File "/home/darryl/Projects/fairscale/tests/nn/data_parallel/test_fsdp_multiple_forward_checkpoint.py", line 200, in _distributed_worker
E           loss.backward()
E         File "/home/darryl/miniconda3/lib/python3.8/site-packages/torch/_tensor.py", line 255, in backward
E           torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
E         File "/home/darryl/miniconda3/lib/python3.8/site-packages/torch/autograd/__init__.py", line 147, in backward
E           Variable._execution_engine.run_backward(
E         File "/home/darryl/miniconda3/lib/python3.8/site-packages/torch/autograd/function.py", line 87, in apply
E           return self._forward_cls.backward(self, *args)  # type: ignore[attr-defined]
E         File "/home/darryl/Projects/fairscale/fairscale/nn/checkpoint/checkpoint_activations.py", line 323, in backward
E           torch.autograd.backward(outputs_with_grad, args_with_grad)
E         File "/home/darryl/miniconda3/lib/python3.8/site-packages/torch/autograd/__init__.py", line 147, in backward
E           Variable._execution_engine.run_backward(
E       RuntimeError: The size of tensor a (720600) must match the size of tensor b (1441200) at non-singleton dimension 0
```

**Comment by min-xu-ai** [comment]
Great! Thanks for the additional info.

1. for the diff, it doesn't seem to apply cleanly on the top of the master branch. Maybe you can just paste the full test code you have in a gist (gist.github.com)?
2. for the maintain_forward_counter argument, it is NOT a performance optimization currently. It is needed to deal with correctness of multiple firing of backward hooks. If we don't use it, it will fail exactly the error you are seeing with a shard dimension mismatch.  I am not sure this is the race condition you are referring to. I do see that with that counter, we delay sharding module's gradient tensors, so I can see it cause OOM. In our previous tests, I have missed this OOM case. There might be ways to avoid this OOM at the cost of more networking traffic (extra grad sharding and all-gather).

Please send us the full test code and let me know if having it not crashing with the dimension error and OOM is sufficient for your use case or not.

**Comment by dbarnhart** [comment]
We can continue discussion in the other issue, but I can eventually have a fix as a PR. I have prototyped something that appears to work well enough.
