### ISSUE TITLE
[test] need a test to cover the checkpoint disabling API

### ISSUE THREAD

**Issue by min-xu-ai** [facebookresearch/fairscale#778]
see issue #771

**Comment by JARACH-209** [comment]
@min-xu-ai  I can try adding a unit test for PR. Had a look at the issues, I hope it will be simple enough! but I would highly appreciate it if you can give some pointers to begin with.

**Comment by min-xu-ai** [comment]
Hi Thank you @JARACH-209 !

Please see issue #771 and the linked commit there. A new API is added to checkpoint_wrapper where you can use a context to disable checkpoint.

I am thinking you can test it this way:

```
class TestModel(nn.Module):
   def __init__(self):
       self.cnt = 0

   def forward(self, x):
       self.cnt +=1
       return x
```

Using the test model above, you can check how many times the self.cnt counter is incremented in the forward function. Then, in a unit test (check examples in `tests` dir), you can make a test where the model is checkpointed with and without the new context API. Then you can assert that without the disable context, the self.cnt value is 2 and with the disable context, the self.cnt value is 1.

Of course, you need to run the model under the checkpoint wrapper with 1 iteration, i.e. 1 forward and 1 backward.

let me know if you have additional questions.
