### ISSUE TITLE
Race condition in gradient reduction

### ISSUE THREAD

**Issue by dbarnhart** [facebookresearch/fairscale#780]
Following up on the previous issue, as I couldn't reopen: https://github.com/facebookresearch/fairscale/issues/777

There seems to be a more fundamental issue here unrelated to mixed precision, and the race condition I mentioned in that issue appears real.

When `method FC` is used, enabling `maintain_forward_counter` in `checkpoint_wrapper` is not optional, as I would expect.

The forward counters seem like a trade-off. With them, you can reduce network overhead at the cost of more VRAM, by retaining the full parameters until the last backward. But in my use case, I have multiple large modules called like Sequence[A, B, C, .., A, B, C...]. I want to reshard after both forward and backward, so using the counters is undesirable.

The unit test fails to capture this error, because the weight tensors are so small that the race condition I was concerned about actually happens. If you make the weights a little larger or force synchronous gradient reduction, the test will fail, without the forward counters. See the diffs below for how to trigger it.

These errors could be avoided with stronger consistency in FSDP's internal state. In my code, I partially avoid the problem by using `method CF` with some small hacks, but the race condition is still technically present. Perhaps a better solution would use `register_full_backward_hook` or similar to detect when we have completed the backward pass for the FSDP module, and reset the appropriate state. Also have a barrier in place to ensure any previous async reduction work is done before the next pre-backward call. This was discussed in the previous issue as well.

Diff for unit test
```
diff --git a/tests/nn/data_parallel/test_fsdp_multiple_forward_checkpoint.py b/tests/nn/data_parallel/test_fsdp_multiple_forward_checkpoint.py
index b4127bc..6776e79 100644
--- a/tests/nn/data_parallel/test_fsdp_multiple_forward_checkpoint.py
+++ b/tests/nn/data_parallel/test_fsdp_multiple_forward_checkpoint.py
@@ -56,10 +56,10 @@ class Model2(nn.Module):
 
     def __init__(self):
         super().__init__()
-        self.block1 = nn.Sequential(nn.Conv2d(3, 4, kernel_size=3), nn.BatchNorm2d(4), nn.ReLU(inplace=True))
-        self.block2 = nn.Sequential(nn.Conv2d(4, 4, kernel_size=3), nn.BatchNorm2d(4), nn.ReLU(inplace=False))
-        self.block3 = nn.Sequential(nn.Conv2d(4, 8, kernel_size=3), nn.BatchNorm2d(8), nn.ReLU(inplace=True))
-        self.head = nn.Sequential(nn.AdaptiveAvgPool2d(output_size=(1, 1)), nn.Flatten(), nn.Linear(8, 10))
+        self.block1 = nn.Sequential(nn.Conv2d(3, 400, kernel_size=3), nn.BatchNorm2d(400), nn.ReLU(inplace=True))
+        self.block2 = nn.Sequential(nn.Conv2d(400, 400, kernel_size=3), nn.BatchNorm2d(400), nn.ReLU(inplace=False))
+        self.block3 = nn.Sequential(nn.Conv2d(400, 800, kernel_size=3), nn.BatchNorm2d(800), nn.ReLU(inplace=True))
+        self.head = nn.Sequential(nn.AdaptiveAvgPool2d(output_size=(1, 1)), nn.Flatten(), nn.Linear(800, 10))
 
     def forward(self, x):
         if isinstance(x, torch.Tensor):
@@ -91,9 +91,9 @@ def _create_model(
             if with_model2:
                 model.block3 = auto_wrap_bn(model.block3, single_rank_pg=False, fsdp_config=fsdp_config)
         if with_checkpoint:
-            model.block2 = checkpoint_wrapper(model.block2, maintain_forward_counter=True)
+            model.block2 = checkpoint_wrapper(model.block2, maintain_forward_counter=False)
             if with_model2:
-                model.block3 = checkpoint_wrapper(model.block3, maintain_forward_counter=True)
+                model.block3 = checkpoint_wrapper(model.block3, maintain_forward_counter=False)
         with enable_wrap(
             wrapper_cls=FSDP,
             flatten_parameters=flatten,
```

Alternatively, force synchronous reduction, and the unit test will fail with small weights.
```
diff --git a/fairscale/nn/data_parallel/fully_sharded_data_parallel.py b/fairscale/nn/data_parallel/fully_sharded_data_parallel.py
index f9a75c8..b77bc08 100644
--- a/fairscale/nn/data_parallel/fully_sharded_data_parallel.py
+++ b/fairscale/nn/data_parallel/fully_sharded_data_parallel.py
@@ -1360,6 +1360,8 @@ class FullyShardedDataParallel(nn.Module):
                 assert self._reducer is not None
                 grad_chunks = chunk_and_pad(param.grad.data, self.world_size)
                 self._reducer.reduce_scatter_async(grad_chunks, group=self.process_group, callback_fn=callback_fn)
+                self._reducer.flush()
+                self._streams["post_backward"].synchronize()
             else:
                 # Currently the only way for _is_sharded to be False is if
                 # world_size == 1. This could be relaxed in the future, in which
```

Example error:

`NCCL_P2P_DISABLE=1 python -m pytest -s tests/nn/data_parallel/test_fsdp_multiple_forward_checkpoint.py::test_multiple_forward_checkpoint[bn-model2-no_auto_wrap_bn-flatten-full]`
```
E       torch.multiprocessing.spawn.ProcessRaisedException: 
E       
E       -- Process 1 terminated with the following error:
E       Traceback (most recent call last):
E         File "/home/darryl/miniconda3/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 59, in _wrap
E           fn(i, *args)
E         File "/home/darryl/Projects/fairscale/tests/nn/data_parallel/test_fsdp_multiple_forward_checkpoint.py", line 200, in _distributed_worker
E           loss.backward()
E         File "/home/darryl/miniconda3/lib/python3.8/site-packages/torch/_tensor.py", line 255, in backward
E           torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
E         File "/home/darryl/miniconda3/lib/python3.8/site-packages/torch/autograd/__init__.py", line 147, in backward
E           Variable._execution_engine.run_backward(
E         File "/home/darryl/miniconda3/lib/python3.8/site-packages/torch/autograd/function.py", line 87, in apply
E           return self._forward_cls.backward(self, *args)  # type: ignore[attr-defined]
E         File "/home/darryl/Projects/fairscale/fairscale/nn/checkpoint/checkpoint_activations.py", line 323, in backward
E           torch.autograd.backward(outputs_with_grad, args_with_grad)
E         File "/home/darryl/miniconda3/lib/python3.8/site-packages/torch/autograd/__init__.py", line 147, in backward
E           Variable._execution_engine.run_backward(
E       RuntimeError: The size of tensor a (720600) must match the size of tensor b (1441200) at non-singleton dimension 0
```

**Comment by min-xu-ai** [comment]
Thanks again. Sorry about the not being able to reopen. I didn't know that you don't have the ability to reopen. Opening a new issue is probably better for clarity anyway. If you have the PR, feel free to send it even if it is in draft mode. Maybe we can review and discuss better around the code.

**Comment by dbarnhart** [comment]
So the "race condition" is really between the reducer bucket filling, and the rest of the backward pass. You can also replicate the error by setting `maintain_forward_counter=False` and `bucket_cap_mb=0`.

I'll have a PR tomorrow that fixes this robustly.

**Comment by zhaojuanmao** [comment]
@dbarnhart I'm wondering why grad reduction/reshard helps in your application? the full parameter needs to be gathered anyway before next forward pass. feel reshard will not reduce peak memory, curious about your case

**Comment by zhaojuanmao** [comment]
@dbarnhart oh, sorry, never mind, I mixed parameters and grads!

**Comment by dbarnhart** [comment]
For those reading later, the issue happens when the call order is [A, B, C, A, B, C]. If we defer gradient reduction and parameter freeing, we require enough memory to gather the _entire_ model and gradients. In the backward pass, we have execution order [C, B, A, C, B, A], and the model state in memory evolves as [C, CB, CBA, CBA, BA, A]. But if we can reduce/reshard immediately, then the model state evolves as [C, B, A, C, B, A], so lower peak usage.

**Comment by min-xu-ai** [comment]
Yeah, very good summary @dbarnhart!

We have had grad accumulation between iterations ( without no_sync() context, hence saving peak memory). This PR very cleanly extended that ability to within an iteration. Super nice!

**Comment by zhaojuanmao** [comment]
> For those reading later, the issue happens when the call order is [A, B, C, A, B, C]. If we defer gradient reduction and full parameter freeing, we require enough memory to gather the _entire_ model and gradients. In the backward pass, we have execution order [C, B, A, C, B, A], and the in-memory model state evolves as [C, CB, CBA, CBA, BA, A]. But if we can reduce/reshard immediately, then the in-memory model state evolves as [C, B, A, C, B, A], so lower peak usage.

thanks for your explanation!
