### ISSUE TITLE
AssertionError: Different devices for the bucket and the param, cannot proceed: cuda:4 - cpu

### ISSUE THREAD

**Issue by gongbudaizhe** [facebookresearch/fairscale#782]
## ❓ Questions and Help
When training adopts ShardedDDP, it fails with this error:

```
  File "python3.6/site-packages/fairscale-0.4.0-py3.6.egg/fairscale/nn/
misc/param_bucket.py", line 69, in add_param                                                                      
    self._add_param_as_view(param)                                                                                
  File "python3.6/site-packages/torch/autograd/grad_mode.py", line 27, 
in decorate_context                                                                                               
    return func(*args, **kwargs)                                                                                  
  File "python3.6/site-packages/fairscale-0.4.0-py3.6.egg/fairscale/nn/
misc/param_bucket.py", line 81, in _add_param_as_view                                                             
    ), f"Different devices for the bucket and the param, cannot proceed: {param.device} - {self.buffer.device}"   
AssertionError: Different devices for the bucket and the param, cannot proceed: cuda:4 - cpu
```

**Comment by min-xu-ai** [comment]
It seems that your model is not entirely on the GPU. The parameter is on the GPU but some buffer are on the CPU. You could change the assert above and print out the param and self.buffer's shape. Perhaps then you can figure out which tensors are them to debug your model further? CC: @blefaudeux

**Comment by blefaudeux** [comment]
Exactly this, than you @min-xu-ai, looks like some params have been moved to cpu (or swapped after the wrap by ShardedDDP with a component which was on cpu ?). 

Basically the ShardedDDP wrap should happen last, when your model is ready to start training (it's also generally true of DDP and FSDP wraps I think)

**Comment by gongbudaizhe** [comment]
By following the advice in #781 , logging messages are more informative and it reveals that some operations involve tensors from both CPU and CUDA. After tackling these mismatches one by one, the problem is solved!

It is worth noting that these mismatches do not cause problems if DDP is used. I guess DDP handles these mismatches internally.

Thanks!

**Comment by blefaudeux** [comment]
@gongbudaizhe OSS does some tensor rearranging behind your back (it uses bigger tensors to act as "hosts" for the smaller ones, which become tensor views), so it's a bit more sensitive to device mismatches, but in any case (even with pure DDP) you'll win out of having everything set up on the same device ! Glad that everything works for you
