### ISSUE TITLE
different iterations have different learnable parameters

### ISSUE THREAD

**Issue by amsword** [facebookresearch/fairscale#785]
## ❓ Questions and Help

Hello,

A general question. does ShardedDDP/OSS support the case when different iterations have different learnable parameters? i tried once, but find it hangs after about 10 iterations.

**Comment by blefaudeux** [comment]
Hi, it supports that through ShardedDDP, if `auto_refresh_trainable` is set to true ([see](https://fairscale.readthedocs.io/en/latest/api/nn/sharded_ddp.html)). If you're using OSS alone then it cannot detect the change by itself, but you can call `.refresh_trainable()` to update the graph.

If the above does not work as expected, I'm interested in a repro, that's a bug !

**Comment by amsword** [comment]
Thanks for confirmation. The program is working now, without any change I can think of.
