### ISSUE TITLE
Does FullyShardedDataParallel support exponential moving average (EMA) of model parameters?

### ISSUE THREAD

**Issue by gongbudaizhe** [facebookresearch/fairscale#789]
## ❓ Questions and Help

Keeping exponential moving average (EMA) of model parameters is a common technique used in model training. I am wondering if this is efficiently supported in FullyShardedDataParallel. 

For now, the params are assembled in forward pass and then resharded. For EMA, the params need to be assembled again,  
this will slow down the training process.  Is this the case? if so, how to efficiently implement EMA in FullyShardedDataParallel?

**Comment by min-xu-ai** [comment]
I think this can be done although we don't have an explicit test for it.

The inefficient way is to use `summon_full_params` API and compute the moving average on the full param.

Likely, you might be able to do it directly on the shards without using `summon_full_params`.

You are welcome to add a unit test to test this out. If there is a bug, we can look into fixing. See tests/nn/data_parallel for a collection of tests.

**Comment by min-xu-ai** [comment]
Assume there is no more questions here.

**Comment by logicwong** [comment]
> I think this can be done although we don't have an explicit test for it.
> 
> The inefficient way is to use `summon_full_params` API and compute the moving average on the full param.
> 
> Likely, you might be able to do it directly on the shards without using `summon_full_params`.
> 
> You are welcome to add a unit test to test this out. If there is a bug, we can look into fixing. See tests/nn/data_parallel for a collection of tests.

@min-xu-ai Hi, I would like to know how to compute the moving average on the shards without using `summon_full_params`? Can you give me some suggestions?

**Comment by min-xu-ai** [comment]
You can do something like this pseudo code:

```
for p in fsdp_wrapped_module.parameters():
    ema.data.mul_(decay)
    ema.data += p.data * (1-decay)
```

Again, it is just pseudo code. Just to illustrate that you loop over all params of a shard without using the summon API.

**Comment by logicwong** [comment]
@min-xu-ai Thanks for your quick reply, I will try it.
