### ISSUE TITLE
Allreduce modules that are ignored by auto_wrap

### ISSUE THREAD

**Issue by ilmarkov** [facebookresearch/fairscale#791]
## ❓ Questions and Help
`auto_wrap`  seems to ignore modules that have less than 1e8 elements by default - the default parameter of `default_auto_wrap_policy` (that would be nice to be mentioned in the documentation).

The question is what happens with the ignored modules in the case of FSDP. If they are not wrapped by FSDP, do they follow the usual DataParallel, i.e. they are all_reduced every step?

If those modules are not all_reduced, could you suggest how to use FSDP for the wrapped modules and `torch.nn.parallel.DistributedDataParallel` for the others?

fairscale: 0.4.0

**Comment by min-xu-ai** [comment]
Oh, sorry for the confusion. The non-wrap module should be wrapped by an outer layer of FSDP in the end. No, DDP is not needed and it is not advised to mix DDP and FSDP.

I.e. with pseudo code:

```
model = Model()
with enable_wrap:
    model = auto_wrap(model)
model = FSDP(model)
```
Maybe auto_wrap really should be renamed to "auto_wrap_inner_layers" or something like that. cc: @zhaojuanmao

**Comment by anj-s** [comment]
@min-xu-ai  why not wrap the entire model as well when we return from auto_wrap if the outer model's params meet the conditions? Are there use cases where we don't want to do this?

**Comment by min-xu-ai** [comment]
Good idea. Maybe it was intended but somehow not doing it due to a bug? Perhaps a boolean argument for this would be nice.

**Comment by anj-s** [comment]
Maybe we can repurpose this issue to track this effort or do you think we should open a new issue? This seems like a nice onboarding issue for someone to take on :)

**Comment by min-xu-ai** [comment]
Of course, I am fine either way. Feel free to do organize it as you see fit.

**Comment by ilmarkov** [comment]
@min-xu-ai Thank you for the answer. It is still unclear for me why user can't wrap the entire model with FSDP to have all child modules synchronized with the same API as `torch.nn.parallel.DistributedDataParallel`. Are there cases when user wraps not the entire model but only large parts of them without need to synchronize the others?

Could you also explain the difference between wrapping a module with FSDP and wrapping the module's children with FSDP? The documentation only says that there is performance difference but it's unclear how the framework behaves in these cases.

**Comment by min-xu-ai** [comment]
> these

We should improve the doc. Feel free to send a PR to us. The difference is that wrapping inner children enables FSDP to shard the parameters in a more memory efficient way. I.e. by wrapping the models with multiple FSDP instances, the parameters are grouped into each FSDP instances, which in turn shard them and free the memory as soon as the computation is done with the parameters during both forward and backward passes. This is important to enable very very large scale models.
