### ISSUE TITLE
Do I need to upgrade my internet interface controller to 40GB or 100GB when I do parallel on multi-machine？

### ISSUE THREAD

**Issue by ljz756245026** [facebookresearch/fairscale#793]
## ❓ Questions and Help
I did some experiment on multi-machine.However, I found that it is really slow on training. I tried to find the reason. Finally, I found that the amount of communication data  is huge and the communication time cost a lot,which is more than 90% of the total running time. My internet interface controller(NIC) is GB NIC， whose highest bandwidth is around 1000 Mbit/s. Thus, I womder know whether it is necessary to upgrade my NIC to 40GB or 100GB NIC.
I am looking forward to your answer.Thank you!

**Comment by min-xu-ai** [comment]
Yes. It is likely too slow. Also, it depends on a lot of other things, like batch size, model size, mixed precision, etc. those can change the impact of network performance in training as well.

**Comment by ljz756245026** [comment]
Thank you for your immediate reply！

**Comment by ljz756245026** [comment]
> Yes. It is likely too slow. Also, it depends on a lot of other things, like batch size, model size, mixed precision, etc. those can change the impact of network performance in training as well.

Thank you for your immediate reply！
