### ISSUE TITLE
layerdrop would cause model training to hang when used with fsdp backend

### ISSUE THREAD

**Issue by arbabu123** [facebookresearch/fairscale#796]
## 🐛 Bug

If you try train a model with fully_sharded backend and use layer drop, the model training will hang. Each individual layer was also wrapped with fsdp in my particular case. It will be good if fairscale can warn about this issue when it happens to avoid people wasting time trying to debug the hang.

**Comment by min-xu-ai** [comment]
Thanks @arbabu123 for filing! This may not be easy to detect in FSDP. We will think about a potential solution.

**Comment by arbabu123** [comment]
Workaround would be rewriting layerdrop as something like 

        for i, layer in enumerate(self.layers):
            dropout_probability = np.random.random()
            if not self.training or (dropout_probability > self.layerdrop):
                mul_factor=1
            else:
                mul_factor=0

            layer_out, z = layer(x, self_attn_padding_mask=padding_mask, need_weights=False)
            if mul_factor > 0:
                x = layer_out
            else:
                x = x

**Comment by min-xu-ai** [comment]
@zhaojuanmao @mrshenli, how about we start a wiki page in pytorch on "FSDP FAQ" to include information like this? I think there are a lot tribal knowledge and tips and tricks that people have accumulated over how to best use FSDP. A FAQ wiki might be useful to future users. What do you think?

**Comment by zhaojuanmao** [comment]
@min-xu-ai sounds a great idea, let me start one and start with this issue:)
