### ISSUE TITLE
Support for Checkpointing and Offloading Without Requiring a Sequential Based Model

### ISSUE THREAD

**Issue by stanleyshly** [facebookresearch/fairscale#862]
## 🚀 Feature
Title
## Motivation
Deepspeed, and some other offloading frameworks don't require a sequential based model for offloading or gradient checkpointing. It would be nice to not need to port models to a NN.sequential format, and it would the barrier to try out existing SOTA models a lot lower. 

## Pitch
Not much can go here, update fairscale to work without NN.sequential?
For sure, this would be a very very large change, but I think this change could make fairscale a much more attractive option for running larger models.

**Comment by visionscaper** [comment]
What are the challenges of generalising `OffloadModel` beyond `nn.Sequential` models? I'm very interested in this topic. Who can shed more light on this? Thanks.
