### ISSUE TITLE
Bug for using grad_scaler.py

### ISSUE THREAD

**Issue by foreveronehundred** [facebookresearch/fairscale#867]
Function _maybe_opt_step cannot be found (line 316 in grad_scaler.py).

**Comment by min-xu-ai** [comment]
cc @anj-s  @anupambhatnagar

**Comment by anj-s** [comment]
@foreveronehundred can you give me more info about the PyTorch version you are running? Can you provide a small repro?

**Comment by foreveronehundred** [comment]
> @foreveronehundred can you give me more info about the PyTorch version you are running? Can you provide a small repro?

1.8.0

**Comment by anupambhatnagar** [comment]
This is being caused due to the torch version and not fairscale. As mentioned in issue #868 we recommend using torch 1.8.1.
