### ISSUE TITLE
Problem of grad_scaler.py with pytorch 1.8.0

### ISSUE THREAD

**Issue by foreveronehundred** [facebookresearch/fairscale#868]
The following line does not work for pytorch 1.8.0. Please fix it. Thanks.
from torch.cuda.amp.common import amp_definitely_not_available

**Comment by min-xu-ai** [comment]
cc @anj-s @anupambhatnagar

**Comment by anj-s** [comment]
Is this different than https://github.com/facebookresearch/fairscale/issues/867 because you are using a different PyTorch version?
Just to let you know, we have standardized our testing for the [following](https://github.com/facebookresearch/fairscale#testing) PyTorch versions

**Comment by anupambhatnagar** [comment]
torch 1.8.0 has no file called `common.py` in `torch/cuda/amp` folder hence the import will never work. We strongly recommend rolling forward to 1.8.1. The code has been tested with that version.

**Comment by anj-s** [comment]
Here is the exact version of PyTorch we are testing on:https://github.com/facebookresearch/fairscale/blob/main/.circleci/config.yml#L82

**Comment by anj-s** [comment]
Let us know if you run into any other issues post updating the PyTorch version.
