### ISSUE TITLE
[MoE] How to do expert sharding?

### ISSUE THREAD

**Issue by gongbudaizhe** [facebookresearch/fairscale#871]
## ❓ Questions and Help

MoE models have a different expert on each gpu device. Therefore, these expert parameters should *not* be allreduced during backward pass. 

To achieve this, p.expert is set to True as shown in:
https://github.com/facebookresearch/fairscale/blob/562542478a145fae410cb23ffd46a8d7c2497abb/fairscale/nn/moe/moe_layer.py#L62-L64

My question is, how is p.expert used in DDP? Is this attribute automatically handled in ShardedDataParallel and FullyShardedDataParallel to disable allreduce?

**Comment by anj-s** [comment]
@gongbudaizhe To ensure that the experts are not allreduced across all GPUs you'll need to [set the process group](https://github.com/facebookresearch/fairscale/blob/main/fairscale/nn/data_parallel/fully_sharded_data_parallel.py#L286) of the expert when you instantiate the model with FSDP. The number of GPUs in the process group will be equal to 1 as expected. This should handle the BW pass. cc @shruti-bh  who has more experience with this.

ShardedDataParallel does not handle this. I would recommend using FullyShardedDataParallel. If you need to prevent sharding of parameters, you can set the parameter [reshard_after_forward=False](https://github.com/facebookresearch/fairscale/blob/main/fairscale/nn/data_parallel/fully_sharded_data_parallel.py#L287) when you wrap the model with FSDP. This should give you the same behavior as ShardedDataParallel.

cc @mrshenli  regarding DDP's implementation of MoE layers. I am not sure how you would prevent allreduce through the MoE layer.

**Comment by gongbudaizhe** [comment]
Thank you for your prompt reply. 

If we need to set the process group to shard the expert parameters, then what is the purpose of setting p.expert = True ?

**Comment by mrshenli** [comment]
> cc @mrshenli regarding DDP's implementation of MoE layers. I am not sure how you would prevent allreduce through the MoE layer.

There is a private `_set_params_and_buffers_to_ignore_for_model` API to tell DDP to ignore params and buffers. See the function below: 

https://github.com/pytorch/pytorch/blob/6ae34ea6f8b65d2ad36e417c3d525507901cfd7f/torch/nn/parallel/distributed.py#L1557-L1581

**Comment by gongbudaizhe** [comment]
For me, FSDP is hard to work with since exponential moving average of params is needed in my model. 

By simply using DDP, MoE works fine. Thanks.
