### ISSUE TITLE
Add the ability to turn off trainable params changed warning

### ISSUE THREAD

**Issue by visionscaper** [facebookresearch/fairscale#874]
## ❓ Questions and Help
I'm posing this as a question, but it is actually a (very small) feature request.

To my understanding, when using `ShardedDDP` with `auto_refresh_trainable=True` (which is the default), I do not have to manually call `refresh_trainable()` when changing the model into `eval()` mode. Yet, while training, whenever I change the model to eval mode, to evaluate the model's validation set performance, I get this warning:

```
WARNING : root::_detect_train_change : ShardedDDP detected that the trainable params changed, either because of eval/train mode or parameter freezing/unfreeze.
```

Although I might be able to suppress any warning logs it is not what I want; I only would like to suppress this specific warning as it is superfluous and occurs every time I switch to eval model to evaluate my model during training.

Would it be possible to add a parameter to the `ShardedDDP` constructor that allows me to disable this warning?
E.g. a `warn_on_trainable_params_changed`, which could be `True` by default.

**Comment by anj-s** [comment]
That makes sense! I suspect we can't figure out when the user has intentionally changed the trainability of params.

**Comment by visionscaper** [comment]
Hi @anj-s, I took the liberty to create a PR for this, let me know what you think. You're welcome to use the fix if you want.
