### ISSUE TITLE
Auto wrapping Huggingface models with FullyShardedDataParallel can break them

### ISSUE THREAD

**Issue by visionscaper** [facebookresearch/fairscale#876]
## 🐛 Bug

If you auto wrap a HuggingFace model with `FullyShardedDataParallel`, depending on what sub-modules are wrapped, and how the output of the modules are accessed in the model, calling `forward` can result in exceptions. 

## What happens

Some sub-modules of the HuggingFace model output a child implementation of [`ModelOutput`](https://github.com/huggingface/transformers/blob/8b240a06617455eae59e1116af6a1a016664e963/src/transformers/file_utils.py#L1884), which is itself a descendent of `OrderedDict`.

An example is, for instance, [`CausalLMOutputWithCrossAttentions` ](https://github.com/huggingface/transformers/blob/8b240a06617455eae59e1116af6a1a016664e963/src/transformers/modeling_outputs.py#L375).

You can access attributes of `ModelOutput` instance derivatives in three ways, e.g. like this:

- `hidden_states = transformer_outputs[0]`
- `hidden_states = transformer_outputs.hidden_states`
- `hidden_states = transformer_outputs["hidden_states"]`

In the HuggingFace library these three types of accessing attributes are used interchangeably.

Now, when a sub-module, which outputs a `ModelOutput` derived instance,  is wrapped with `FullyShardedDataParallel`, this output instance is converted in to an `OrderedDict`, in the [`apply_to_tensors`](https://github.com/facebookresearch/fairscale/blob/fecb665b812b6bfc38442e1fb1557e21508917f4/fairscale/utils/containers.py#L21) function, in `utils/containers.py`, since the `ModelOutput` derives from `OrderedDict`! :

```
        elif isinstance(x, OrderedDict):
            od = OrderedDict()
            for key, value in x.items():
                od[key] = _apply(value)
            return od
```

After it has been converted into a plain `OrderedDict` by `FullyShardedDataParallel`, when the output of the submodule is, for instance, accessed using an index (`transformer_outputs[0]`) or attribute accessor (`transformer_outputs. hidden_states`), an exception is thrown, because the `OrderedDict` instance doesn't know how to handle that. 

## A simple solution

A simple solution is to replace the `OrderedDict` instantiation above with `od = x.__class__()`, thus:

```
        elif isinstance(x, OrderedDict):
            od = x.__class__()
            for key, value in x.items():
                od[key] = _apply(value)
            return od
```

In this way we keep on using the original class, with its extended means to access attributes, which is used in the HuggingFace library.

## To Reproduce

1. Use a HuggingFace model, e.g. `GPT2LMHeadModel`
```
from transformers import GPT2Config, GPT2LMHeadModel
```

2. Build the model 
```
        # You could also try, e.g. "gpt2-large"
        model_config = GPT2Config.from_pretrained("gpt2")
        self._model = GPT2LMHeadModel(model_config)

        self._model.to(self._device)
```

3. Auto wrap the model
```
                wrap_policy = functools.partial(default_auto_wrap_policy,
                                                min_num_params=1e8)

                fsdp_params = {
                    "mixed_precision": False,
                    "move_params_to_cpu": False
                }

                with enable_wrap(wrapper_cls=FullyShardedDDP, auto_wrap_policy=wrap_policy, **fsdp_params):
                    self._training_model = auto_wrap(self._model)

                # Finally wrap root module
                self._training_model = FullyShardedDDP(self._training_model, **fsdp_params)
```

4. Use this in a training loop

This results in errors similar to this one where the `OrderedDict` accessed in invalid ways:
```
... transformers/models/gpt2/modeling_gpt2.py", line 1057, in forward
    hidden_states = transformer_outputs[0]
KeyError: 0
```

## Expected behavior

No exception should occur, `FullyShardedDataParallel` should not break calling the HuggingFace model.

## Environment

```
$ pip show fairscale
Name: fairscale
Version: 0.4.3

$ pip show transformers
Name: transformers
Version: 4.12.5

$ pip show torch
Name: torch
Version: 1.10.0

$ python --version
Python 3.7.4
```

**Comment by visionscaper** [comment]
^ Updated the issue text, by accident published it early.

**Comment by min-xu-ai** [comment]
Is there a way to use a custom wrapping policy instead of the default_auto_wrap_policy function in this case? FSDP can't easily detect what is a safe boundary for wrapping a sub-module.

**Comment by visionscaper** [comment]
Hi @min-xu-ai, uhm, maybe, if you, for instance, look at the [`GPT2LMHeadModel`](https://github.com/huggingface/transformers/blob/6fc38adff272ea3148e05888edf67eeb00170453/src/transformers/models/gpt2/modeling_gpt2.py#L943) you can find natural boundaries, such as the [decoder blocks](https://github.com/huggingface/transformers/blob/6fc38adff272ea3148e05888edf67eeb00170453/src/transformers/models/gpt2/modeling_gpt2.py#L887) of the used `GPT2Model`. But if you would wrap these blocks with FSDP, you will get an exception a few lines further, because the outputs of the blocks is accessed using indexed based accessing (`hidden_states = outputs[0]`). So you would need to go a level-deeper, or a level higher (which is the whole transformer decoder). So it is not ideal in my opinion.

But wouldn't the simple fix I suggested make FAIRScale more stable? Or are you worried about some sort of side effect of this fix?

**Comment by visionscaper** [comment]
PS: In the trainer.py of the Huggingface Transformers repo, [models are wrapped only on the top level](https://github.com/huggingface/transformers/blob/6fc38adff272ea3148e05888edf67eeb00170453/src/transformers/trainer.py#L982), hence the issue does not occur:

```
                if ShardedDDPOption.AUTO_WRAP in self.args.sharded_ddp:
                    model = auto_wrap(model)
                self.model = model = FullyShardedDDP(
                    model,
                    mixed_precision=mixed_precision,
                    reshard_after_forward=zero_3,
                    cpu_offload=cpu_offload,
                ).to(self.args.device)
```
Although, using the `ShardedDDPOption.AUTO_WRAP` option might cause issues.

**Comment by min-xu-ai** [comment]
Sorry, I read your Report too quickly. You are right. The fix seems to be reasonable. The only potential issue is when x.__class__() fails when it expects some mandatory Args.

Feel free to send us a PR. Thanks!
