### ISSUE TITLE
[FSDP] reshard_after_forward = False for root instance

### ISSUE THREAD

**Issue by foreveronehundred** [facebookresearch/fairscale#878]
```
if self._is_root:
    # Buffers stay on GPU, and don't get sharded. Since _cast_buffers
    # applies recursively, we only call this from the root instance.
    self._cast_buffers()
            
    # Don't free the full params for the outer-most (root) instance,
    # since those params will be needed immediately after for the
    # backward pass.
    self.reshard_after_forward = False

    # Due to the use of streams, we need to make sure the previous
    # ``optim.step()`` is done before we all-gather parameters.
    self._wait_for_previous_optim_step()
```
According to the following code (from fully_sharded_data_parallel.py), we can find that reshard_after_forward is set to False for root instance (for better performance). However, when we use autowrap() to wrap model, we only wrap leaf nodes, i.e., every leaf is an FSDP root instance. In this case, every FSDP instance's reshard_after_forward will be set to False even if we set reshard_after_forward to True (in initialization). However, due to a memory issue, I still want to reshard after forward when wrapping with autowrap(). 
I have a few questions,
1. Could I just comment "self.reshard_after_forward = False" as an work around solution?
2. Could you add a parameter in __init__() of FullyShardedDataParallel to decide whether self.reshard_after_forward need to be set to False for root instance?
3. For the FSDP wrapping using autowrap(), is the performance affected by the reshard_after_forward? Since the FSDP instances in this case are not outer-most (root) instances, these params will not be needed immediately for the backward pass

**Comment by min-xu-ai** [comment]
Only the root should have it set to force and won't affect memory usage. See PR #880 to fix a bug related to this.

**Comment by min-xu-ai** [comment]
You can checkout `min/fix` branch or apply the patch yourself to see if my fix fixes your issue.

**Comment by foreveronehundred** [comment]
Again, I want to emphasize that in my case, I used autowrap() and I only wrapped leaf modules. So, every wrapped modules is a FSDP root module, and every module will not be resharded since it is a root FSDP module. It is what we want because when these modules (except the last module) can be reshard to save memory after their forward finishes (backward will not happen immediately).

**Comment by min-xu-ai** [comment]
I see. That’s a case we don’t currently test. The workaround you are using is likely fine. Feel free to send us a PR with FSDP changes and with unit test if you want this case supported. We can take a look for sure. Thanks!
