### ISSUE TITLE
Why should we exclude MultiheadAttention for FSDP wrapping in default_auto_wrap_policy?

### ISSUE THREAD

**Issue by foreveronehundred** [facebookresearch/fairscale#899]
I saw in the default_auto_wrap_policy (auto_wrap.py), you exclude MultiheadAttention when applying autowrap. 
https://github.com/facebookresearch/fairscale/blob/main/fairscale/nn/wrap/auto_wrap.py#L71

However, I have tried to wrap MultiheadAttention layer with FSDP, and the training result was correct without making any mistake. May I know the reason why you decide to exclude MultiheadAttention  when FSDP wrapping?

**Comment by min-xu-ai** [comment]
We didn't exclude it in the wrapping. The code you are referring is trying not to wrap a sub-module within the MHA module. We will still wrap it just not let auto_wrapper to break MHA into different FSDP instances.

Hope this answers your questions. Please just reopen if it doesn't answer all of your questions. Thanks!
