### ISSUE TITLE
FSDP: Can't work with megatron bert/gpt model

### ISSUE THREAD

**Issue by jerryli1981** [facebookresearch/fairscale#901]
Even when I didn't use model parallel from megatron, I still can't let megatron model work with FSDP       
--tensor-model-parallel-size 1 \
--pipeline-model-parallel-size 1 \

   output_parallel = F.linear(input_parallel, self.weight, bias)

   return torch._C._nn.linear(input, weight, bias)
RuntimeError: setStorage: sizes [768, 2304], strides [1, 768], storage offset 87985152, and itemsize 4 requiring a storage size of 7077888 are out of bounds for storage of size 0

i22b09327:107836:107836 [0] init.cc:924 NCCL WARN Cuda failure 'an illegal memory access was encountered'
terminate called after throwing an instance of 'std::runtime_error'
  what():  NCCL error in: /pytorch/torch/lib/c10d/../c10d/NCCLUtils.hpp:155, unhandled cuda error, NCCL version 2.7.8
ncclUnhandledCudaError: Call to CUDA function failed.

**Comment by min-xu-ai** [comment]
We haven't made any effort in testing FSDP with Megatron yet. Thanks for reporting nonetheless.

Can you share a more complete version of test that fails on you? Please make sure it is as simple, as short as possible. Thanks a lot!

**Comment by anj-s** [comment]
cc @ngoyal2707

**Comment by ZhongYingMatrix** [comment]
bias returned by RowParallelLinear or ColumnParallelLinear is Parameters which gets free storage after FSDP forward

**Comment by anj-s** [comment]
Please reopen once you have a repro. Thanks!
