### ISSUE TITLE
FSDP fails with multiple forward and then multiple backward calls

### ISSUE THREAD

**Issue by ngoyal2707** [facebookresearch/fairscale#918]
I have a use case where I need to do multiple forward calls and then backwards call instead of usual pattern but FSDP throws following error when calling multiple backwards:

```
Asserting FSDP instance is: FullyShardedDataParallel(
  world_size=2, flatten_parameters=True, mixed_precision=False,
  (_fsdp_wrapped_module_test): FlattenParamsWrapper(
    (_fpw_module): FFN(
      (fc1): Linear(in_features=10, out_features=10, bias=True)
      (fc2): Linear(in_features=10, out_features=10, bias=True)
      (relu): ReLU()
    )
  )
)
ERROR: expected to be in states [<TrainingState.BACKWARD_POST: 4>] but current state is TrainingState.BACKWARD_PRE
```

Code to repro error: 
```
import torch
import torch.nn as nn
import argparse
from fairscale.nn.data_parallel import FullyShardedDataParallel
from fairscale.nn import enable_wrap
from fairscale.nn import wrap


class FFN(nn.Module):
    def __init__(self):
        super().__init__()
        self.fc1 = nn.Linear(10, 10)
        self.fc2 = nn.Linear(10, 10)
        self.relu = nn.ReLU()
    
    def forward(self, x):
        return self.fc2(self.relu(self.fc1(x)))


def main(i, args):
    torch.manual_seed(0)
    torch.cuda.manual_seed(0)
    print(i)
    torch.cuda.set_device(i)
    torch.distributed.init_process_group(
        backend='nccl',
        init_method='tcp://localhost:22345',
        world_size=args.world_size,
        rank=i,
    )
    ffn = FFN()

    with enable_wrap(
        wrapper_cls=FullyShardedDataParallel
    ):
        model = wrap(
            ffn,
            process_group=torch.distributed.new_group(),
            flatten_parameters=True,
            compute_dtype=torch.float16
        ).half()

    model = model.train()

    x1 = torch.rand((10, 10)).cuda().half()
    out1 = model(x1)
    loss1 = out1.sum()
    
    x2 = torch.rand((10, 10)).cuda().half()
    out2 = model(x2)
    loss2 = out2.sum()
    
    with model.no_sync():
        loss1.backward()
        loss2.backward()

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--world-size', '--ws', type=int)
    args = parser.parse_args()
    torch.multiprocessing.spawn(
        fn=main, 
        args=(args, ),
        nprocs=min(
            torch.cuda.device_count(),
            args.world_size,
        ),
        join=True,
    )
```

**Comment by anj-s** [comment]
I see 2 losses that are different from the use case that we have covered in our tests [here](https://github.com/facebookresearch/fairscale/blob/0a526bcbe212b043a00a5bdfae73c7ef532c88b4/tests/nn/data_parallel/test_fsdp_grad_acc.py#L96). Does the error happen on the second BW call? Can you also share a complete stack trace of the error?

**Comment by ngoyal2707** [comment]
Full stack trace: 

I might have some local changes so the lines may not lineup with whats in main
```
ERROR: expected to be in states [<TrainingState.BACKWARD_POST: 4>] but current state is TrainingState.BACKWARD_PRE
  File "/home/namangoyal/.conda/envs/fairseq-20220105/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/namangoyal/rsc/fairseq_gshard/fairseq-py/fairscale/nn/data_parallel/fully_sharded_data_parallel.py", line 1473, in _wait_for_post_backward
    self.assert_state(TrainingState.BACKWARD_POST)
  File "/home/namangoyal/rsc/fairseq_gshard/fairseq-py/fairscale/nn/data_parallel/fully_sharded_data_parallel.py", line 1891, in assert_state
    traceback.print_stack()
1 True False TrainingState.IDLE
1 True False TrainingState.IDLE
Traceback (most recent call last):
  File "/home/namangoyal/.conda/envs/fairseq-20220105/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/namangoyal/.conda/envs/fairseq-20220105/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/namangoyal/rsc/fairseq_gshard/fairseq-py/scripts/test_fsdp/multiple_backward.py", line 69, in <module>
    torch.multiprocessing.spawn(
  File "/home/namangoyal/.conda/envs/fairseq-20220105/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 240, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/namangoyal/.conda/envs/fairseq-20220105/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 198, in start_processes
    while not context.join():
  File "/home/namangoyal/.conda/envs/fairseq-20220105/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 160, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException:

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/home/namangoyal/.conda/envs/fairseq-20220105/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File "/home/namangoyal/rsc/fairseq_gshard/fairseq-py/scripts/test_fsdp/multiple_backward.py", line 59, in main
    loss2.backward()
  File "/home/namangoyal/.conda/envs/fairseq-20220105/lib/python3.9/site-packages/torch/_tensor.py", line 352, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/home/namangoyal/.conda/envs/fairseq-20220105/lib/python3.9/site-packages/torch/autograd/__init__.py", line 173, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
SystemError: <built-in method run_backward of torch._C._EngineBase object at 0x7fd5ac2e4c40> returned NULL without setting an error
```

**Comment by min-xu-ai** [comment]
cc @zhaojuanmao for this use case as well.

we tested

```
loss1 = fwd()
loss1.backward()
loss2 = fwd()
loss2.backward()
```

This new use case is different. The assert msg means that FSDP wrapper expects to see the backward hooks firing in certain order but it was not.

does this use case work with DDP? Also, why delay calling loss1.backward()? It seems OK to backward on it first and then do the second fwd on x2, right? Doing it in the example you have seems to only increase the GPU memory needed for the activations. Am I missing something?

**Comment by ngoyal2707** [comment]
@min-xu-ai yes it works with DDP and its required currently for my usecase of combining FSDP with pipeline parallel cause the backward of a microbatch is delayed.

**Comment by min-xu-ai** [comment]
I suspect that the problem is with pre-backward hooks, which is installed on the output tensor using register_hook. For models that runs part of a module's fwd function multiple times, we have a guard that prevents pre-backward hook to run multiple times.

<img width="923" alt="image" src="https://user-images.githubusercontent.com/24926999/150874309-84fc5112-206f-4331-8818-92a4eedd07a5.png">


This guard is reset at the end of each backward, but I suspect the use of `no_sync` context prevented that. What if you remove the no_sync context? no_sync + grad_accumulation is not ideal for FSDP IMHO since it consumes more memory due to the un-synced gradients.

**Comment by ngoyal2707** [comment]
It still fails without the no_sync context. 
`no_sync + grad_accumulation is not ideal for FSDP`, I am not sure about this, basically the goal is to do adam state sharding without doing model weights sharding, which is deepspeed zero stage 2.

**Comment by min-xu-ai** [comment]
Ah, I see. That makes a lot of sense. 

I think you meant zero stage 1 though. Since in stage 2 you would shard the gradients. For sharping only the Adam state, perhaps using ddp + oss.py would be simpler for you? Just an idea.

**Comment by anj-s** [comment]
@ngoyal2707  Is there an action item for us to follow up here or will you be trying what Min suggested? Want to make sure we unblock your use case if needed.

**Comment by ngoyal2707** [comment]
@anj-s I still think action item is to basically support above use-case with FSDP. I understand that gradients wont be sharded due to `no_sync` but I dont see any technical reason to not support this use-case.

**Comment by lmelinda** [comment]
Hi, I'm experiencing a similar error:
```
Asserting FSDP instance is: FullyShardedDataParallel(
  (_fsdp_wrapped_module): FlattenParamsWrapper(
    (_fpw_module): Linear(in_features=2, out_features=128, bias=True)
  )
)
ERROR: expected to be in states [<TrainingState_.BACKWARD_PRE: 3>, <TrainingState_.BACKWARD_POST: 4>] but current state is TrainingState_.IDLE
```

I'm on PyTorch 1.13 so I should have the fix mentioned here. I'm running backward on one loss. Have we seen this error before?

**Comment by min-xu-ai** [comment]
Thanks for reporting. Do you have a small reproducible test case?

**Comment by lmelinda** [comment]
I've quite tried but unfortunately couldn't isolate a smaller snippet, as the model is big and it seemed to be related to something that happens during the forward pass. I tried to mock forward outputs and the loss backward would work fine. It's a bit hard and likely unproductive to dig out which part in the forward pass is causing this.

one interesting thing (not sure if helpful) I found is, the module that is giving error is `Linear(in_features=2, out_features=128, bias=True)`. My model has 3 of them, and `_register_pre_backward_hooks` is called to register all of them. However, 2 of this module actually runs the hook `_pre_backward_hook`, but the last module `_pre_backward_hook` didn't get called, before `_post_backward_hook` got called.
Would this ring any bells?

**Comment by min-xu-ai** [comment]
some ideas:

1. have you tried disable flattening? In FSDP init, you can set flatten_parameters to false. That may side-step the issue.
2. how did you wrap the model with multiple FSDP wrappers? You need nested wrapping to fully realize the memory gain by FSDP. It is worth trying different wrapping to see if the issue can be avoided.

Finally, in general the debugging process looks like the following:

- modify the fsdp code so that each backward callback prints out which FSDP instance it is (using object ID or some kind of name. Since multiple FSDP instances can be wrapping exactly same structure of a submodule, just printing out self.module from FSDP might not be enough (since they look the same).
- run you code and inspect the order of backward hooks firing on each of the instance above
- for example if the wrapping looks like the following:
```
fsdp0(
  fsdp1()
  fsdp2()
)
```
then, the backward hook firing order needs to look like:
```
fsdp0.pre-back
fsdp2.pre-back
fsdp2.post-back
fsdp1.pre-back
fsdp1.post-back
fsdp0.post-back
```

(I just listed above from memory, it could be slightly wrong. Please double check the code and assertion.)

If the order is not correct, it is usually due to autograd engine make different param.grad ready order in the backward. You can try to see if there are way you can modify your code so that autograd will make the right backward order that FSDP can work with.

I know this is not an easy process. If someone else have better ideas, please let me know.

**Comment by lmelinda** [comment]
1. I'm on PyTorch v1.13 and I don't see the option for `flatten_parameters`.
2. I don't think I have multiple FSDP wrappers? It's elements like `ModuleDict` or `Sequential` where they could have multiple `Linear`s under the hood.  I have a single call for wrapping `FSDP(model)`. I don't intend to create multiple FSDP wrappers, let me know if I constructed it wrong.
3. I could look into using module names to see if that gives anything different, I was printing out `handle.module` in all the hook functions, i didn't know `.module` would look the same (not sure if I fully understand why either lol)

**Comment by min-xu-ai** [comment]
I see. Perhaps you are using pytorch version of FSDP? I was talking about fairscale version, which is different and in maintenance mode. If you are using pytorch version, please check with pytorch github issue page and raise your question there.

For nested wrapping, you can check some unit test examples in the tests dir within this repo.
