### ISSUE TITLE
Some FSDP tests fail on A100 due to tensorfloat32

### ISSUE THREAD

**Issue by myleott** [facebookresearch/fairscale#921]
Some of the FSDP tests check that DDP and FSDP outputs match exactly. However, on PyTorch will silently use tensorfloat32 (TF32) on A100s, which makes the results not match exactly.

**Repro:**

This test fails on A100:
```bash
$ pytest tests/nn/data_parallel/test_fsdp_grad_acc.py::TestGradAcc::test_transformer
(...)
E       Mismatched elements: 2288 / 8423 (27.2%)
E       Greatest absolute difference: 0.0031833648681640625 at index 2528 (up to 1e-05 allowed)
E       Greatest relative difference: 13.919027977044477 at index 1155 (up to 0.0001 allowed)
```

It will pass if we disable tf32:
```python
# tests/nn/data_parallel/test_fsdp_grad_acc.py
(...)
torch.backends.cuda.matmul.allow_tf32 = False
torch.backends.cudnn.allow_tf32 = False
(...)
```

**Suggestion:**

Should we disable TF32 on all unit tests? Or change the tolerance for these tests on A100s?

Thanks to @ngoyal2707 for helping debug this :)

**Comment by min-xu-ai** [comment]
cc @zhaojuanmao. This seems like something production code cares even more?

For me, I feel disable tf32 is better since it keeps a tight check on parity. To me, changing tolerance may allow future precision changing commits to slip through without us knowing it. WDYT?

**Comment by myleott** [comment]
Agreed, disabling TF32 seems better, esp. for tests

**Comment by min-xu-ai** [comment]
I can do this later for all FSDP tests. But I don't have an A100 to test though. Feel free to do it yourself too.

**Comment by zhaojuanmao** [comment]
> cc @zhaojuanmao. This seems like something production code cares even more?
> 
> For me, I feel disable tf32 is better since it keeps a tight check on parity. To me, changing tolerance may allow future precision changing commits to slip through without us knowing it. WDYT?

Thanks for letting me know. Yes, we usually disable tf32 in unit tests because of the precision issue. will watch out this in PT version

**Comment by min-xu-ai** [comment]
FWIW, looks like pytorch is going to switch default to TF32 being disabled. So I think this could be closed. Reopen if more is needed.
