### ISSUE TITLE
[feat] Make Adascale work with Adam optimizer

### ISSUE THREAD

**Issue by suchenzang** [facebookresearch/fairscale#928]
See discussion thread here: https://fb.workplace.com/notes/160155753018370/?comment_id=160309839669628&reply_comment_id=160369649663647

**Comment by min-xu-ai** [comment]
Using adascale to wrap Adam is already supported. However, the effect of it might not be as good as that for SGD. Basically, once you wrapped your Adam with AdaScale, you will get a new optimizer object that internally adjust the LR according to the signals (gradients) from each distributed worker.

So please go ahead and try it if you want. There is no code changes needed from fairscale side as far as I can tell.

**Comment by suchenzang** [comment]
@min-xu-ai should documentation be updated to reflect that? https://fairscale.readthedocs.io/en/latest/deep_dive/adascale.html makes it seem it's only compatible with SGD from a code compatibility perspective

**Comment by min-xu-ai** [comment]
Yes, it is true. For now perhaps we can leave it as it since we may not want general people to use it with Adam. You are not general people. :-)
