### ISSUE TITLE
bfloat16 for sharded grad scaler

### ISSUE THREAD

**Issue by LeeDoYup** [facebookresearch/fairscale#931]
Thanks for the awesome project.
I wonder that whether the sharded gradient scaler of fairscale supports amp with bfloat16 or not.

**Comment by min-xu-ai** [comment]
Thank you for the nice words! We are glad that you like fairscale.

I don't think bfloat16 is supported by any of the library.

**Comment by LeeDoYup** [comment]
thanks for the fast reply.
However, I read that pytorch amp supports bfloat16 recently.

https://medium.com/m/global-identity?redirectUrl=https%3A%2F%2Fdevblog.pytorchlightning.ai%2Fintroducing-faster-training-with-lightning-and-brain-float16-861505eabbfc

**Comment by min-xu-ai** [comment]
Yeah, pytorch support doesn't mean fairscale automatically support bfloat16 unfortunately.

**Comment by LeeDoYup** [comment]
I understood. Thank you very much @min-xu-ai !!
