### ISSUE TITLE
[OSS] Out of Memory When Calling "optimizer.state_dict(all_ranks=True)"

### ISSUE THREAD

**Issue by foreveronehundred** [facebookresearch/fairscale#937]
I was training my model with 8 GPUs, and I wrapped the optimizer with OSS. As title, when I called optimizer.state_dict(all_ranks=True), I got the following error messages,
```
  File "/home/xxx/.local/lib/python3.8/site-packages/fairscale/optim/oss.py", line 399, in state_dict
    self.consolidate_state_dict(recipient_rank=-1)
  File "/home/xxx/.local/lib/python3.8/site-packages/fairscale/optim/oss.py", line 357, in consolidate_state_dict
    dist.broadcast_object_list(
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 1699, in broadcast_object_list
    object_list[i] = _tensor_to_object(obj_view, obj_size)
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 1418, in _tensor_to_object
    out = pickle.loads(buf)
  File "/opt/conda/lib/python3.8/site-packages/torch/storage.py", line 161, in _load_from_bytes
    return torch.load(io.BytesIO(b))
  File "/opt/conda/lib/python3.8/site-packages/torch/serialization.py", line 593, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/opt/conda/lib/python3.8/site-packages/torch/serialization.py", line 772, in _legacy_load
    result = unpickler.load()
  File "/opt/conda/lib/python3.8/site-packages/torch/serialization.py", line 728, in persistent_load
    deserialized_objects[root_key] = restore_location(obj, location)
  File "/opt/conda/lib/python3.8/site-packages/torch/serialization.py", line 175, in default_restore_location
    result = fn(storage, location)
  File "/opt/conda/lib/python3.8/site-packages/torch/serialization.py", line 155, in _cuda_deserialize
    return storage_type(obj.size())
  File "/opt/conda/lib/python3.8/site-packages/torch/cuda/__init__.py", line 484, in _lazy_new
    return super(_CudaBase, cls).__new__(cls, *args, **kwargs)
RuntimeError: CUDA error: out of memory
```
Since my model can be trained without using the OSS, I think the root cause may not be the model size.

**Comment by anj-s** [comment]
@foreveronehundred Since we perform other operations related to consolidating optimizer state, using OSS vs vanilla training might have different behavior. Any chance you have a repro that you can share? What is the size of the model? Do you see this error on a smaller model?

**Comment by foreveronehundred** [comment]
Hi, 
     Sorry for the late reply. First, let me give some details about the environment of the training job. We use 8 V100 GPUs with pytorch-1.8.0-cuda11.1-cudnn8.
     Actually, I found that this problem can be avoided by using smaller models. However I still found a strange thing when calling broadcast_object_list in consolidate_state_dict.
     In the case of smaller model, I found that before calling broadcast_object_list, the reserved memory is around 13 GB, and after calling broadcast_object_list the reserved memory is larger than 20 GB. The difference is much larger than the my model.

**Comment by foreveronehundred** [comment]
As a workaround, I found that using _broadcast_object will not cause the above problem. Could your team add a new arg that can force the code to use _broadcast_object? If It is not convenient for you, could I help you to modify and make a pull request?

**Comment by anj-s** [comment]
@foreveronehundred Sounds good! Can you tell me more about the root cause of the issue? happy to modify but would be good to know when it does not work and why. Thanks for debugging this!

**Comment by foreveronehundred** [comment]
> @foreveronehundred Sounds good! Can you tell me more about the root cause of the issue? happy to modify but would be good to know when it does not work and why. Thanks for debugging this!

Sorry, I do not know the root cause of the issue, but I will try to help you reproduce the problem I found.

The problem came from broadcast_object_list in consolidate_state_dict. So first, please run a task that calls OSS and consolidate_state_dict, and make sure that broadcast_object_list is called. Then, please profile memory before/after the call of consolidate_state_dict or broadcast_object_list . When profiling the memory, please do not use the API from torch.cuda, just use nvidia-smi. I think in this way you can find the increase of memory.

**Comment by foreveronehundred** [comment]
By the way, could you tell me when you will finish add the arg I have mentioned?

**Comment by foreveronehundred** [comment]
> > By the way, could you tell me when you will finish add the arg I have mentioned?
> 
> @foreveronehundred It might take me a bit to get to this. Feel free to send a PR to help fix this. Thanks!

Just make a pull request. Please review it and tell me if there is any problem.
https://github.com/facebookresearch/fairscale/pull/942

**Comment by min-xu-ai** [comment]
@anj-s, I remember you mentioned that you wanted to remove OSS and SDP. Do pytorch team already have those features and have a stable owner for them? If so, maybe we should just either remove ours or turn ours into a wrapper to the pytorch version?

**Comment by foreveronehundred** [comment]
> Hi @foreveronehundred, have you tried https://pytorch.org/docs/stable/distributed.optim.html#torch.distributed.optim.ZeroRedundancyOptimizer ? It's basically the follow up from OSS in fairscale (a fork initially), but should be better supported at the moment, may resolve your problem out of the box (which does look like a bug in how NCCL caches data, strange but could be because of the calls being async and a lot of buffers being in flight at any point in time).

Thanks for recommendation. I want to know that is there any improvement of performance and memory saving for torch.distributed.optim.ZeroRedundancyOptimizer compared to OSS?

**Comment by foreveronehundred** [comment]
> @anj-s, I remember you mentioned that you wanted to remove OSS and SDP. Do pytorch team already have those features and have a stable owner for them? If so, maybe we should just either remove ours or turn ours into a wrapper to the pytorch version?

Do you mean OSS will be replaced by torch.distributed.optim.ZeroRedundancyOptimizer?
Then, what will Sharded DDP?

**Comment by anj-s** [comment]
@foreveronehundred We have planned deprecation for OSS since it has been upstreamed to PyTorch as the [ZeroRedundancyOptimizer](https://pytorch.org/tutorials/recipes/zero_redundancy_optimizer.html). ShardedDataParallel can be enabled as part of the FullyShardedDataParallel API by setting the `no_reshard_after_forward` parameter to be False. We don't have any comparison benchmarks for OSS vs ZeroRedundancyOptimizer AFAIK. 

@min-xu-ai They do have a stable owner for OSS and given FSDP encompasses SDP's functionality we can deprecate both the APIs.
