### ISSUE TITLE
About memory utilization of FSDP

### ISSUE THREAD

**Issue by Youhe-Jiang** [facebookresearch/fairscale#940]
When using FSDP for multi-machine distributed experiments, I found that the display results of nvidia-smi and the display results of torch.cuda.max_memory_allocated(device) are very different. Which tool should I prefer?

**Comment by tmarkstrum** [comment]
I suggest using torch.cuda.max_memory_allocated(device)

**Comment by Youhe-Jiang** [comment]
> 

Now I'm totally clear. Thank you for your reply : ) .

**Comment by DK223** [comment]
> > 
> 
> Now I'm totally clear. Thank you for your reply : ) .

Hi, I meet the same question with you. The reduction between torch.cuda.max_memory_allocated() and nvidia-smi is different a lot when using FSDP. Do you know the reason?

**Comment by min-xu-ai** [comment]
> Hi, I meet the same question with you. The reduction between torch.cuda.max_memory_allocated() and nvidia-smi is different a lot when using FSDP. Do you know the reason?

This is expected since max_memory_allocated is from pytorch's allocator point of view. nvidia-smi report all memory used including pytorch and other libraries like NCCL etc.  You might be able to find more info from pytorch's developers on their discussion forum.

**Comment by Youhe-Jiang** [comment]
> > Hi, I meet the same question with you. The reduction between torch.cuda.max_memory_allocated() and nvidia-smi is different a lot when using FSDP. Do you know the reason?
> 
> This is expected since max_memory_allocated is from pytorch's allocator point of view. nvidia-smi report all memory used including pytorch and other libraries like NCCL etc. You might be able to find more info from pytorch's developers on their discussion forum.

Yeah, it is recommended to use the former as the benchmark for judging the real memory usage of the GPU
