### ISSUE TITLE
[APEX] Can we use Apex amp together with OSS/ShardedDDP

### ISSUE THREAD

**Issue by foreveronehundred** [facebookresearch/fairscale#941]
As title can we use Apex amp together with OSS/ShardedDDP?

**Comment by anj-s** [comment]
Here is discussion and suggestions for how to go about this: https://github.com/facebookresearch/fairscale/issues/740

**Comment by min-xu-ai** [comment]
@foreveronehundred can this be closed or do you have additional questions?
