### ISSUE TITLE
[ShardedDDP] Optimizers with different process groups

### ISSUE THREAD

**Issue by foreveronehundred** [facebookresearch/fairscale#943]
I am now using ShardedDataParallel with sharded_optimizer (a list of optimizers). 
However, in my case, the corresponding process group of each optimizer is different, 
and it may not be the same as the keyword arg, process_group, of class ShardedDataParallel. 
Can the current ShardedDataParallel support my case?

**Comment by blefaudeux** [comment]
hi @foreveronehundred, thanks for creating the issue and reporting this usecase ! I'll defer to @anj-s and @min-xu-ai, but these days I would recommend using FSDP with the "no reshard" option, the featureset is comparable to shardedDDP and it is more future proof and probably faster. 
To reply specifically to your question I don't think that ShardedDDP supports this case right now, it could have been added but again it's in the process of being deprecated. 
Happy training, I hope that FSDP helps !

**Comment by min-xu-ai** [comment]
@foreveronehundred, can you share some simple code to show what exactly do you want to do? With that I can tell you whether FSDP will work with it or not.

**Comment by foreveronehundred** [comment]
I am now dealing with MoE model. So, different blocks may not share the same process group.
I know that FSDP can be applied to my case. However, I want to compare the memory saving and performance for OSS, Sharded DDP and FSDP, so I still need to try Sharded DDP.

**Comment by foreveronehundred** [comment]
> hi @foreveronehundred, thanks for creating the issue and reporting this usecase ! I'll defer to @anj-s and @min-xu-ai, but these days I would recommend using FSDP with the "no reshard" option, the featureset is comparable to shardedDDP and it is more future proof and probably faster. To reply specifically to your question I don't think that ShardedDDP supports this case right now, it could have been added but again it's in the process of being deprecated. Happy training, I hope that FSDP helps !

I did not find the "no shard" option in FSDP. Could you help me to find that?

**Comment by anj-s** [comment]
@foreveronehundred The toggle is called `[reshard_after_forward](https://fairscale.readthedocs.io/en/latest/api/nn/fsdp.html)`. Setting it False makes FSDP equivalent to SDP.

**Comment by min-xu-ai** [comment]
hi @foreveronehundred, can you send email to m1n -at- fb.com so that we can discuss things besides this issue? Thanks!

**Comment by foreveronehundred** [comment]
I just modified the ShardedDDP.py to support the scenario in this issue. Several variables in my code become a dict (keys are the names of different process groups, and values remain the original types). Feel free to share ideas for my code.
https://github.com/foreveronehundred/fairscale/commit/9f9b8b42e18bbbce4cad4756367a555d2ff8c3fb

**Comment by blefaudeux** [comment]
oh interesting, thanks for sharing @foreveronehundred ! Any perf numbers to share ? micro optim by the way, but accessing a list is a bit faster than a dict, so if the ordering never changes you might as well store things in a list (may be too negligible though, I don't have a good feeling for your hotspots). @tmarkstrum  did you have any news to share on FSDP and zero-2, just in case you find something ? :)
