### ISSUE TITLE
Can FSDP() and Pipe() API be used at the same time?

### ISSUE THREAD

**Issue by Youhe-Jiang** [facebookresearch/fairscale#945]
Can FSDP() and Pipe() API be used at the same time? Thanks for any useful advice!

**Comment by min-xu-ai** [comment]
no, that has not being supported or tested. It may work but it really depends on the details of how do you combine them.

**Comment by min-xu-ai** [comment]
Also, pipe API is moving /has moved to pytorch. I don't think we are continue developing it here in fairscale.

**Comment by Youhe-Jiang** [comment]
> 
Thanks a lot for your reply! :)

**Comment by flying-x** [comment]
could this closed? Feel free to share what you have tried and found out.
