### ISSUE TITLE
Is it possible to run Pipe along with FSDP?

### ISSUE THREAD

**Issue by BinhangYuan** [facebookresearch/fairscale#958]
Based on my understanding the current pipeline implementation can only work for an instance with multiple GPUs, right?

If I want to further scale out my training procedure, can I combine Pipe with FSDP? For example, run Pipe intra- a single multi-GPU instance, while run FSDP across multiple GPU instances?

Is there any relevant example for this? Thanks for your great help!

**Comment by anj-s** [comment]
> Based on my understanding the current pipeline implementation can only work for an instance with multiple GPUs, right?
Yes, that is correct.
> If I want to further scale out my training procedure, can I combine Pipe with FSDP? For example, run Pipe intra- a single multi-GPU instance, while run FSDP across multiple GPU instances?
we haven't tried it out but there might be some changes to how we initialize and run the model's FW/BW pass.
> Is there any relevant example for this? Thanks for your great help!
Sorry, unfortunately we don't have one. If you implement this we would appreciate a PR contribution from you!
