### ISSUE TITLE
Broken pip fairscale package

### ISSUE THREAD

**Issue by Vittorio-Caggiano** [facebookresearch/fairscale#96]
## 🐛 Bug

There is an error with the installation of the fairscale package 

## Command
pip install fairscale
## Reproduce
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-vc622m0j/fairscale/setup.py", line 10, in <module>
        import torch
    ModuleNotFoundError: No module named 'torch'

**Comment by msbaines** [comment]
I am not able to reproduce. I see the following:

```
Requirement already satisfied: numpy in /private/home/msb/.conda/envs/fairseq-20200116-pytorch-151/lib/python3.6/site-packages (from torch>=1.4.0->│
fairscale) (1.17.4)                                                                                                                                │
Requirement already satisfied: future in /private/home/msb/.conda/envs/fairseq-20200116-pytorch-151/lib/python3.6/site-packages (from torch>=1.4.0-│
>fairscale) (0.18.2)                                                                                                                               │
Installing collected packages: torch, fairscale                                                                                                    │
Successfully installed fairscale-0.0.2 torch-1.6.0   
```

Which OS are you running?

Install dependencies seem to be correct are handled via https://github.com/facebookresearch/fairscale/blob/master/setup.py#L57.

**Comment by Vittorio-Caggiano** [comment]
Solved the issue: by default a new environment is created with `pip == 9.0.1`. In order to install the dependencies pip needs to be upgraded to the latest version e.g. 20.2.3
