### ISSUE TITLE
Fairscale Anaconda incompatible with recent pytorch release

### ISSUE THREAD

**Issue by ebetica** [facebookresearch/fairscale#960]
```
conda install -d -c pytorch conda-forge::fairscale=0.4.6 pytorch::pytorch=1.11.0
...
  - package fairscale-0.4.6-cpu_py38h66f0ec1_0 requires pytorch >=1.10.2,<1.11.0a0, but none of the providers can be installed
```

I think fairscale should allow for the recently 1.11 release, this may be as simple as changing the version requirements on conda.

**Comment by min-xu-ai** [comment]
This is probably a related to how Conda fariscale version is built. Can you file an issue with Conda?

**Comment by ebetica** [comment]
I didn't realize somebody at anaconda was building these. I can look into it, thanks.
