### ISSUE TITLE
pre-commit seed isort known_third_party failing on main (for me)

### ISSUE THREAD

**Issue by another-pjohnson** [facebookresearch/fairscale#965]
In late January I was able to run the pre-commit hook successfully. Now however, as part of a new PR that I'm working on, I keep on seeing a failure on the seed isort known_third_party step of the pre-commit hook.

Making the suggested change I fail the github automatic pre-commit check on my PR.

I'm wondering if there's some sort of version mismatch.

requirements-dev.txt reports seed-isort-config == 2.2.0, and this is the version that I have.

Here is the change my version wants to make:

```
-known_third_party = ["benchmark_dataset", "datasets", "distutils", "golden_configs", "models", "numpy", "parameterized", "pytest", "recommonmark", "setuptools", "sklearn", "torch", "torchtext", "torchvision", "utils"]
+known_third_party = ["benchmark_dataset", "datasets", "distutils", "golden_configs", "models", "numpy", "parameterized", "pytest", "recommonmark", "setuptools", "sklearn", "torchtext", "torchvision", "utils"]
```

It seems like it wants to remove the "torch" entry.

**Comment by min-xu-ai** [comment]
I ran into this as well. did you try remove .cache/pre-commit dir? You can try to run seed-isort-config by hand and see what it does to you local tree. pre-commit runs it from a shallow repo at the given version but there might be some dependency escaping happening here. Last time I found a dependency on numpy was causing mypy running issues and once I pinned down the numpy version in pre-commit's dependency, it was fixed.

**Comment by another-pjohnson** [comment]
So i've narrowed down the problem. Apparently seed-isort-config generates different results between python 3.8.12 and 3.9.7. I'm not sure if we should codify that requirement, but I'm sure if we could detect this, it would save other's the same headache. (or at least mention it in the CONTRIBUTING.md)

**Comment by another-pjohnson** [comment]
@min-xu-ai Also, according to the seed-isort-config github, this project is no longer needed when using a sort version >= 5.0:

https://github.com/asottile-archive/seed-isort-config#readme

```
DEPRECATED
this is no longer needed as of isort>=5
```

**Comment by min-xu-ai** [comment]
awesome, I think we should just remove it if we are already isort>=5 or just upgrade to isort >=5

**Comment by another-pjohnson** [comment]
isort is already >= 5 from requirements-dev.txt:
```
isort == 5.10.1
```
