### ISSUE TITLE
[FSDP] Some questions for process_group_reduce_scatter 

### ISSUE THREAD

**Issue by foreveronehundred** [facebookresearch/fairscale#968]
Hi, I have some questions for process_group_reduce_scatter,
1. If the arg (process_group_reduce_scatter) is not assigned for FSDP wrapping, the process groups for process_group_reduce_scatter will be the "world", and the group size == GPU count. Is it correct?
2. Could you tell me in what circumstances we will need to set different process groups to process_group and process_group_reduce_scatter? Could you give me an example (model)?

**Comment by foreveronehundred** [comment]
For question 2, I just got the answer from https://github.com/facebookresearch/fairscale/pull/897.
However, there is still one thing I want to conform with you. 
_"Although we create different process groups for sharding and reduce scatter respectively. The members (GPU ranks) of two groups are the same."_
Is the above statement correct?

**Comment by tmarkstrum** [comment]
Yes. the GPU ranks for the two groups are the same. If they are not same, the process falls back to use the default process group.

**Comment by tmarkstrum** [comment]
By default, the two process_group and process_group_reduce_scatter are different process group to enable communication overlap on different layers.

**Comment by foreveronehundred** [comment]
Thanks for your reply.
