### ISSUE TITLE
[FSDP] FSDP() vs. autowrap(), which one has better throughput

### ISSUE THREAD

**Issue by foreveronehundred** [facebookresearch/fairscale#971]
Since FSDP() and autowrap() of FSDP will give different module structure (like following), I want to ask which one has better performance?

```
# autowrap
model.blocks.layer1
model.blocks.layer1._fsdp_wrapped_module
model.blocks.layer1._fsdp_wrapped_module._fpw_module
model.blocks.layer2
model.blocks.layer2._fsdp_wrapped_module
model.blocks.layer2._fsdp_wrapped_module._fpw_module
model.blocks.layer3
model.blocks.layer3._fsdp_wrapped_module
model.blocks.layer3._fsdp_wrapped_module._fpw_module
```

```
# FSDP
_fsdp_wrapped_module._fpw_module.model.blocks.layer1
_fsdp_wrapped_module._fpw_module.model.blocks.layer2
_fsdp_wrapped_module._fpw_module.model.blocks.layer3
```

**Comment by min-xu-ai** [comment]
Sorry for the delay and I was on vacation last week. I think there are 2 aspects here:

(1) which one is faster
(2) which one fits a given GPU memory limit

autowrap one above will have smaller GPU memory consumption but may be slower than the second one where all 3 layers are wrapped by a single FSDP instance. So, the answer is that if the second method fits your GPU memory budget, I think it will be faster. cc @tmarkstrum

**Comment by min-xu-ai** [comment]
Please reopen if you have additional questions.
