### ISSUE TITLE
ssd offload tests are disabled for nightly

### ISSUE THREAD

**Issue by min-xu-ai** [facebookresearch/fairscale#978]
PR #977 disabled them due to updated 1.12 torch version. If they are needed, please re-enable them.

**Comment by another-pjohnson** [comment]
@min-xu-ai After 974, most of the tests are passing, but now gpu_tests_pytorch_nightly-3 is failing on Setup Virtual Environment step. There are no meaningful error messages or logs to see for that step. Any idea what's going on?

**Comment by min-xu-ai** [comment]
I think it is CI's infra problem. I have tried to re-run the failed one a few times. I think it will be fixed at some point. For now, I think this can be closed. Thanks again for helping with this!
