### ISSUE TITLE
An example of AsyncPipe usage

### ISSUE THREAD

**Issue by gaow0007** [facebookresearch/fairscale#985]
Thanks for the contributor of this amazing repo. 

I am read the source code of AsyncPipe, and expect certain concrete exemplary codes to ease the walk-through process. 

May I ask to add one example about how to use asyncPipe?

**Comment by min-xu-ai** [comment]
Thanks for the kind words!

Unfortunately, I don't have expertise in async pipe. The dev did it is no longer working on it. You can try to git blame to find out who worked most on it and try to tag him on github. Or you can try to read through the code and try to figure it out yourself. Sorry about that.

**Comment by gaow0007** [comment]
> Thanks for the kind words!
> 
> Unfortunately, I don't have expertise in async pipe. The dev did it is no longer working on it. You can try to git blame to find out who worked most on it and try to tag him on github. Or you can try to read through the code and try to figure it out yourself. Sorry about that.

Thanks for your reply.
