### ISSUE TITLE
[Bug] OSS - Dataclasses dependences is missing

### ISSUE THREAD

**Issue by Vittorio-Caggiano** [facebookresearch/fairscale#99]
## 🐛 Bug

The module fairscale.optim.oss has a dependence on the package Dataclassess
 
## To Reproduce
1. python -m venv tfs_env
2. source tfs_env/bin/activate
3. git clone https://github.com/facebookresearch/fairscale.git
4. cd fairscale/
5. pip install --upgrade pip
6. pip install fairscale
7. python
8. from fairscale.optim.oss import OSS

```
~/testCode/fairscale/fairscale/__init__.py in <module>
     10 ################################################################################
     11 
---> 12 from . import nn

~/testCode/fairscale/fairscale/nn/__init__.py in <module>
----> 1 from .pipe import Pipe
      2 
      3 __all__ = ["Pipe"]

~/testCode/fairscale/fairscale/nn/pipe/__init__.py in <module>
     20 """A Pipe implementation in PyTorch."""
     21 from .checkpoint import is_checkpointing, is_recomputing
---> 22 from .pipe import Pipe
     23 
     24 __all__ = ["Pipe", "is_checkpointing", "is_recomputing"]

~/testCode/fairscale/fairscale/nn/pipe/pipe.py in <module>
     32 from . import microbatch
     33 from .batchnorm import DeferredBatchNorm
---> 34 from .pipeline import Pipeline, PipelineStyle
     35 from .skip.layout import SkipLayout, inspect_skip_layout
     36 from .skip.skippable import Skippable, verify_skippables

~/testCode/fairscale/fairscale/nn/pipe/pipeline.py in <module>
     26 from typing import TYPE_CHECKING, Any, Dict, Iterable, List, Optional, Tuple, Type, Union, cast
     27 
---> 28 from dataclasses import dataclass
     29 import numpy as np
     30 import torch

ModuleNotFoundError: No module named 'dataclasses'
```

**Comment by blefaudeux** [comment]
it's about the pipe module, not oss, no ?

**Comment by blefaudeux** [comment]
and it looks like you have not installed fairscale. This is typically the error you would get if importing fairscale from a vanilla python environment. See README to either install directly via pip remotely (pip install fairscale) or locally

**Comment by stephenroller** [comment]
dataclasses is distributed with python 3.7 and above, but not python 3.6

**Comment by blefaudeux** [comment]
> dataclasses is distributed with python 3.7 and above, but not python 3.6

so makes sense to add it to requirements.txt, right ?

**Comment by stephenroller** [comment]
I've been unclear if there is harm if you pip install dataclasses on pytorch 3.7.

Also of course, maybe you don't support 3.6, maybe you do. I just saw the issue in notifications and thought I'd mention it

**Comment by moskomule** [comment]
Hugging face’s transformers does ` "dataclasses;python_version<'3.7'", ` in setup.py.

https://github.com/huggingface/transformers/blob/47ab3e8262144cb962fc2769bf7551fc23c3ce2b/setup.py#L115
